/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w -pthread  -I/usr/local/Cellar/nim/0.17.2/nim/lib -o /Users/joshuahorwitz/nim/ChatApp/src/nimcache/stdlib_net.o /Users/joshuahorwitz/nim/ChatApp/src/nimcache/stdlib_net.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <sys/socket.h>
#include <sys/types.h>
#define _GNU_SOURCE
#include <pthread.h>
#include <errno.h>
#include <sys/types.h>
                          #include <pthread.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Option_V9bnQIoRETSshkjE1kDWuNQ tyObject_Option_V9bnQIoRETSshkjE1kDWuNQ;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_GcThread_hgJQSlfXDOK3SwSHjeZBXg tyObject_GcThread_hgJQSlfXDOK3SwSHjeZBXg;
typedef struct Exception Exception;
typedef struct tySequence_WF89a8QyKeDCh4DYWTmSiBg tySequence_WF89a8QyKeDCh4DYWTmSiBg;
typedef struct TGenericSeq TGenericSeq;
typedef struct TSafePoint TSafePoint;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_SharedList_9cWkTIPQvNw7gFHMOEzMCLw tyObject_SharedList_9cWkTIPQvNw7gFHMOEzMCLw;
typedef struct tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw;
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct NimStringDesc NimStringDesc;
typedef struct tyObject_PDispatchercolonObjectType__pnVRciItPqJkU9bkmY2UaWQ tyObject_PDispatchercolonObjectType__pnVRciItPqJkU9bkmY2UaWQ;
typedef NU8 tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg;
struct tyObject_Option_V9bnQIoRETSshkjE1kDWuNQ {
tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg val;
NIM_BOOL has;
};
typedef NU8 tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg;
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tySet_tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg;
typedef NF tyArray_SBX73RxxTewX4sqVYGfdEA[1001];
struct tyObject_GcThread_hgJQSlfXDOK3SwSHjeZBXg {
tyArray_SBX73RxxTewX4sqVYGfdEA tls;
};
typedef NU8 tyEnum_SOBool_SDlZUtKctfhvUZ58547HWQ;
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc_hgOQFBQi19biNdOUUkFOOxA) (Exception* e);
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc_IIomJ6ptE6vfJ5zRbATgkQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI lastSize;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* freeChunksList;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_SharedList_9cWkTIPQvNw7gFHMOEzMCLw {
tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw* head;
tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw* tail;
pthread_mutex_t lock;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
tyObject_SharedList_9cWkTIPQvNw7gFHMOEzMCLw toDispose;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tyProc_IIomJ6ptE6vfJ5zRbATgkQ cbproc, void* ClE_0);
void* ClE_0;
} tyProc_Ig6kXMs9apW5862wHsbFhGw;
struct tySequence_WF89a8QyKeDCh4DYWTmSiBg {
  TGenericSeq Sup;
  tyProc_IIomJ6ptE6vfJ5zRbATgkQ data[SEQ_DECL_SIZE];
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
typedef struct {tyProc_hgOQFBQi19biNdOUUkFOOxA localRaiseHook_EIvMhANBvB9cp2Ezvt29cADg;
tySequence_WF89a8QyKeDCh4DYWTmSiBg* threadDestructionHandlers_8OmU3x0fNdA0DLtOmU3kWw;
NI threadId_wzrdPYhtL9czkCWS4o9an9cRw;
TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
TSafePoint* excHandler_rqLlY5bs9atDw2OXYqJEn5g;
Exception* currException_9bVPeDJlYTi9bQApZpfH8wjg;
tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
NIM_BOOL envComputed_OC1kQm9aRvX8VnmaXglp57Q;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* environment_rnCB7Cc69bd2mlM49cn9czO2Q;
NIM_BOOL isSlave_t9a8wsVVRYqGEKhg1vb49b3g;
tyProc_Ig6kXMs9apW5862wHsbFhGw callSoonProc_9b9b4iUSd60RO2UqC52ifJ6A;
tyObject_PDispatchercolonObjectType__pnVRciItPqJkU9bkmY2UaWQ* gDisp_yIbBArLUsg2pBJkilx4yvg;
} NimThreadVars;
N_NIMCALL(NIM_BOOL, isNone_Q4RsUqhsTDIbkeIguPSpvA)(tyObject_Option_V9bnQIoRETSshkjE1kDWuNQ self);
N_NIMCALL(tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg, unsafeGet_fdGmwO5YUOWb8OBjkhgjng)(tyObject_Option_V9bnQIoRETSshkjE1kDWuNQ self);
N_NIMCALL(NIM_BOOL, isSome_Q4RsUqhsTDIbkeIguPSpvA_2)(tyObject_Option_V9bnQIoRETSshkjE1kDWuNQ self);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void*, GetThreadLocalVars)(void);
static N_INLINE(void*, threadVarGetValue_F5t3jb8jndWAZxsO5Ba9bHwsystem)(pthread_key_t s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
TNimType NTI_4xio0cAXR7XG4pF9bVcpxEg_;
extern pthread_key_t globalsSlot_ciXDZu9c27pHpCRMoz4RIgw;

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void*, threadVarGetValue_F5t3jb8jndWAZxsO5Ba9bHwsystem)(pthread_key_t s) {
	void* result;
	result = (void*)0;
	result = pthread_getspecific(s);
	return result;
}

static N_INLINE(void*, GetThreadLocalVars)(void) {
	void* result;
	void* T1_;
	result = (void*)0;
	T1_ = (void*)0;
	T1_ = threadVarGetValue_F5t3jb8jndWAZxsO5Ba9bHwsystem(globalsSlot_ciXDZu9c27pHpCRMoz4RIgw);
	result = ((void*) ((*((tyObject_GcThread_hgJQSlfXDOK3SwSHjeZBXg*) (T1_))).tls));
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	NimThreadVars* NimTV_;
	NimTV_ = (NimThreadVars*) GetThreadLocalVars();
	T1_ = (NI)0;
	{
		if (!(NimTV_->framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*NimTV_->framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = NimTV_->framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	NimTV_->framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	NimThreadVars* NimTV_;
	NimTV_ = (NimThreadVars*) GetThreadLocalVars();
	NimTV_->framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*NimTV_->framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_NIMCALL(int, toOSFlags_LPk8C9cHJSVIMMTqcH4p4xA)(tySet_tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg socketFlags) {
	int result;
	nimfr_("toOSFlags", "net.nim");
	result = (int)0;
	{
		tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg f;
		NI i;
		f = (tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg)0;
		nimln_(2112, "system.nim");
		i = ((NI) 0);
		{
			nimln_(2113, "system.nim");
			while (1) {
				NI TM_XqsrSBxhOTPgLQ9cX4MmV4A_5;
				if (!(i <= ((NI) 1))) goto LA3;
				nimln_(2114, "system.nim");
				{
					if (!((socketFlags &(1U<<((NU)(((tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg)chckRange(i, ((tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg) 0), ((tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg) 1))))&7U)))!=0)) goto LA6_;
					f = ((tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg)chckRange(i, ((tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg) 0), ((tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg) 1)));
					{
						nimln_(197, "net.nim");
						switch (f) {
						case ((tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg) 0):
						{
							nimln_(199, "net.nim");
							result = (NI32)(result | MSG_PEEK);
						}
						break;
						case ((tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg) 1):
						{
							nimln_(200, "net.nim");
							goto LA8;
						}
						break;
						}
					} LA8: ;
				}
				LA6_: ;
				nimln_(2115, "system.nim");
				TM_XqsrSBxhOTPgLQ9cX4MmV4A_5 = addInt(i, ((NI) 1));
				i = (NI)(TM_XqsrSBxhOTPgLQ9cX4MmV4A_5);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, isDisconnectionError_40p9aaw5rEmIprdUBGKsyYQ)(tySet_tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg flags, NI32 lastError) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	nimfr_("isDisconnectionError", "net.nim");
	result = (NIM_BOOL)0;
	nimln_(184, "net.nim");
	nimln_(191, "net.nim");
	T1_ = (NIM_BOOL)0;
	T1_ = ((flags &(1U<<((NU)(((tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg) 1))&7U)))!=0);
	if (!(T1_)) goto LA2_;
	nimln_(192, "net.nim");
	T1_ = (lastError == ((NI)chckRange(ECONNRESET, ((NI) 0), ((NI) 65535))) || lastError == ((NI)chckRange(EPIPE, ((NI) 0), ((NI) 65535))) || lastError == ((NI)chckRange(ENETRESET, ((NI) 0), ((NI) 65535))));
	LA2_: ;
	result = T1_;
	popFrame();
	return result;
}

N_NIMCALL(int, toCInt_ne8KyyT0jskmnqTgYiJN4w)(tyEnum_SOBool_SDlZUtKctfhvUZ58547HWQ opt) {
	int result;
	nimfr_("toCInt", "net.nim");
	result = (int)0;
	nimln_(870, "net.nim");
	nimln_(871, "net.nim");
	switch (opt) {
	case ((tyEnum_SOBool_SDlZUtKctfhvUZ58547HWQ) 0):
	{
		result = SO_ACCEPTCONN;
	}
	break;
	case ((tyEnum_SOBool_SDlZUtKctfhvUZ58547HWQ) 1):
	{
		result = SO_BROADCAST;
	}
	break;
	case ((tyEnum_SOBool_SDlZUtKctfhvUZ58547HWQ) 2):
	{
		result = SO_DEBUG;
	}
	break;
	case ((tyEnum_SOBool_SDlZUtKctfhvUZ58547HWQ) 3):
	{
		result = SO_DONTROUTE;
	}
	break;
	case ((tyEnum_SOBool_SDlZUtKctfhvUZ58547HWQ) 4):
	{
		result = SO_KEEPALIVE;
	}
	break;
	case ((tyEnum_SOBool_SDlZUtKctfhvUZ58547HWQ) 5):
	{
		result = SO_OOBINLINE;
	}
	break;
	case ((tyEnum_SOBool_SDlZUtKctfhvUZ58547HWQ) 6):
	{
		result = SO_REUSEADDR;
	}
	break;
	case ((tyEnum_SOBool_SDlZUtKctfhvUZ58547HWQ) 7):
	{
		result = SO_REUSEPORT;
	}
	break;
	}
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_netInit000)(void) {
	nimfr_("net", "net.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_netDatInit000)(void) {
static TNimNode* TM_XqsrSBxhOTPgLQ9cX4MmV4A_2[2];
NI TM_XqsrSBxhOTPgLQ9cX4MmV4A_4;
static char* NIM_CONST TM_XqsrSBxhOTPgLQ9cX4MmV4A_3[2] = {
"Peek", 
"SafeDisconn"};
static TNimNode TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[3];
NTI_4xio0cAXR7XG4pF9bVcpxEg_.size = sizeof(tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg);
NTI_4xio0cAXR7XG4pF9bVcpxEg_.kind = 14;
NTI_4xio0cAXR7XG4pF9bVcpxEg_.base = 0;
NTI_4xio0cAXR7XG4pF9bVcpxEg_.flags = 3;
for (TM_XqsrSBxhOTPgLQ9cX4MmV4A_4 = 0; TM_XqsrSBxhOTPgLQ9cX4MmV4A_4 < 2; TM_XqsrSBxhOTPgLQ9cX4MmV4A_4++) {
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[TM_XqsrSBxhOTPgLQ9cX4MmV4A_4+0].kind = 1;
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[TM_XqsrSBxhOTPgLQ9cX4MmV4A_4+0].offset = TM_XqsrSBxhOTPgLQ9cX4MmV4A_4;
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[TM_XqsrSBxhOTPgLQ9cX4MmV4A_4+0].name = TM_XqsrSBxhOTPgLQ9cX4MmV4A_3[TM_XqsrSBxhOTPgLQ9cX4MmV4A_4];
TM_XqsrSBxhOTPgLQ9cX4MmV4A_2[TM_XqsrSBxhOTPgLQ9cX4MmV4A_4] = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[TM_XqsrSBxhOTPgLQ9cX4MmV4A_4+0];
}
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[2].len = 2; TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[2].kind = 2; TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[2].sons = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_2[0];
NTI_4xio0cAXR7XG4pF9bVcpxEg_.node = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[2];
}

