/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w -pthread  -I/usr/local/Cellar/nim/0.17.2/nim/lib -o /Users/joshuahorwitz/nim/ChatApp/src/nimcache/stdlib_locks.o /Users/joshuahorwitz/nim/ChatApp/src/nimcache/stdlib_locks.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <pthread.h>
#include <sys/types.h>
                          #include <pthread.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
static N_INLINE(void, initLock_NyibMGWEvLI6dmuAjxN9brAlocks)(pthread_mutex_t* lock);
static N_INLINE(void, deinitLock_NyibMGWEvLI6dmuAjxN9brA_2locks)(pthread_mutex_t* lock);
N_NIMCALL(NIM_BOOL, tryAcquire_9bPySkj6HXfWNB4ampKcs9bg)(pthread_mutex_t* lock);
N_NIMCALL(void, acquire_c9cbvs4ShkxrwmQmnY63PGA)(pthread_mutex_t* lock);
N_NIMCALL(void, release_c9cbvs4ShkxrwmQmnY63PGA_2)(pthread_mutex_t* lock);
static N_INLINE(void, initCond_cET5UPJTPSiflmV7IZS68Alocks)(pthread_cond_t* cond);
static N_INLINE(void, deinitCond_cET5UPJTPSiflmV7IZS68A_2locks)(pthread_cond_t* cond);
static N_INLINE(void, wait_1jWf7NqlMVz9aQJMRL9bTm9bQlocks)(pthread_cond_t* cond, pthread_mutex_t* lock);
static N_INLINE(void, signal_cET5UPJTPSiflmV7IZS68A_3locks)(pthread_cond_t* cond);
TNimType NTI_keOjwH3s9bnYBEeyteQLwbw_;
TNimType NTI_9bxnxao7MiiLOwO9aLAh9a3og_;

static N_INLINE(void, initLock_NyibMGWEvLI6dmuAjxN9brAlocks)(pthread_mutex_t* lock) {
	pthread_mutex_init(lock, NIM_NIL);
}

static N_INLINE(void, deinitLock_NyibMGWEvLI6dmuAjxN9brA_2locks)(pthread_mutex_t* lock) {
	pthread_mutex_destroy(lock);
}

N_NIMCALL(NIM_BOOL, tryAcquire_9bPySkj6HXfWNB4ampKcs9bg)(pthread_mutex_t* lock) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = pthread_mutex_trylock(lock);
	result = (T1_ == ((NI32) 0));
	return result;
}

N_NIMCALL(void, acquire_c9cbvs4ShkxrwmQmnY63PGA)(pthread_mutex_t* lock) {
	pthread_mutex_lock(lock);
}

N_NIMCALL(void, release_c9cbvs4ShkxrwmQmnY63PGA_2)(pthread_mutex_t* lock) {
	pthread_mutex_unlock(lock);
}

static N_INLINE(void, initCond_cET5UPJTPSiflmV7IZS68Alocks)(pthread_cond_t* cond) {
	pthread_cond_init(cond, NIM_NIL);
}

static N_INLINE(void, deinitCond_cET5UPJTPSiflmV7IZS68A_2locks)(pthread_cond_t* cond) {
	pthread_cond_destroy(cond);
}

static N_INLINE(void, wait_1jWf7NqlMVz9aQJMRL9bTm9bQlocks)(pthread_cond_t* cond, pthread_mutex_t* lock) {
	pthread_cond_wait(cond, lock);
}

static N_INLINE(void, signal_cET5UPJTPSiflmV7IZS68A_3locks)(pthread_cond_t* cond) {
	pthread_cond_signal(cond);
}
NIM_EXTERNC N_NOINLINE(void, stdlib_locksInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, stdlib_locksDatInit000)(void) {
static TNimNode TM_05xOtLU9bCAYnon4m09bcBlg_0[2];
NTI_keOjwH3s9bnYBEeyteQLwbw_.size = sizeof(pthread_cond_t);
NTI_keOjwH3s9bnYBEeyteQLwbw_.kind = 18;
NTI_keOjwH3s9bnYBEeyteQLwbw_.base = 0;
NTI_keOjwH3s9bnYBEeyteQLwbw_.flags = 3;
NTI_keOjwH3s9bnYBEeyteQLwbw_.node = &TM_05xOtLU9bCAYnon4m09bcBlg_0[0];
NTI_9bxnxao7MiiLOwO9aLAh9a3og_.size = sizeof(pthread_mutex_t);
NTI_9bxnxao7MiiLOwO9aLAh9a3og_.kind = 18;
NTI_9bxnxao7MiiLOwO9aLAh9a3og_.base = 0;
NTI_9bxnxao7MiiLOwO9aLAh9a3og_.flags = 3;
NTI_9bxnxao7MiiLOwO9aLAh9a3og_.node = &TM_05xOtLU9bCAYnon4m09bcBlg_0[1];
}

