/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w -pthread  -I/usr/local/Cellar/nim/0.17.2/nim/lib -o /Users/joshuahorwitz/nim/ChatApp/src/nimcache/stdlib_threadpool.o /Users/joshuahorwitz/nim/ChatApp/src/nimcache/stdlib_threadpool.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <pthread.h>
#include <sys/types.h>
                          #include <pthread.h>
#include <sys/types.h>
#define _GNU_SOURCE
#include <pthread.h>
#include <string.h>
#include <setjmp.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Semaphore_sx9abLHOwgGDBH9bpoqw2ezw tyObject_Semaphore_sx9abLHOwgGDBH9bpoqw2ezw;
typedef struct Barrier Barrier;
typedef struct tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_AwaitInfo_InuzBj4ASNnb8C8ZpRzfbA tyObject_AwaitInfo_InuzBj4ASNnb8C8ZpRzfbA;
typedef struct tyObject_GcThread_hgJQSlfXDOK3SwSHjeZBXg tyObject_GcThread_hgJQSlfXDOK3SwSHjeZBXg;
typedef struct tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw;
typedef struct tyObject_ToFreeQueue_5COJP8EWIaAuXvZlDbQZmw tyObject_ToFreeQueue_5COJP8EWIaAuXvZlDbQZmw;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Exception Exception;
typedef struct TSafePoint TSafePoint;
typedef struct tyObject_Thread_r8ouAaNLK65Vq7NM85n5aw tyObject_Thread_r8ouAaNLK65Vq7NM85n5aw;
typedef struct tyObject_ThreadPoolState_jN9benzGjAA9bryIHC1FGnZA tyObject_ThreadPoolState_jN9benzGjAA9bryIHC1FGnZA;
typedef struct tyObject_FlowVarObj_a5vp0WwZohkMPdG8GkZciw tyObject_FlowVarObj_a5vp0WwZohkMPdG8GkZciw;
typedef struct tySequence_WF89a8QyKeDCh4DYWTmSiBg tySequence_WF89a8QyKeDCh4DYWTmSiBg;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_SharedList_9cWkTIPQvNw7gFHMOEzMCLw tyObject_SharedList_9cWkTIPQvNw7gFHMOEzMCLw;
typedef struct tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw;
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tyObject_PDispatchercolonObjectType__pnVRciItPqJkU9bkmY2UaWQ tyObject_PDispatchercolonObjectType__pnVRciItPqJkU9bkmY2UaWQ;
struct tyObject_Semaphore_sx9abLHOwgGDBH9bpoqw2ezw {
pthread_cond_t c;
pthread_mutex_t L;
NI counter;
};
typedef NU8 tyArray_izDbpwaA8Rxj9b5mE6pSF7Q[24];
struct Barrier {
NI entered;
tyObject_Semaphore_sx9abLHOwgGDBH9bpoqw2ezw cv;
NI left;
tyArray_izDbpwaA8Rxj9b5mE6pSF7Q cacheAlign2;
NIM_BOOL interest;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
struct tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg {
  RootObj Sup;
NIM_BOOL ready;
NIM_BOOL usesSemaphore;
NIM_BOOL awaited;
tyObject_Semaphore_sx9abLHOwgGDBH9bpoqw2ezw cv;
tyObject_AwaitInfo_InuzBj4ASNnb8C8ZpRzfbA* ai;
NI idx;
void* data;
void* owner;
};
typedef NF tyArray_SBX73RxxTewX4sqVYGfdEA[1001];
struct tyObject_GcThread_hgJQSlfXDOK3SwSHjeZBXg {
tyArray_SBX73RxxTewX4sqVYGfdEA tls;
};
typedef N_NIMCALL_PTR(void, tyProc_fhqfcnDhIcLpBpSTVsWEZg) (void* thread, void* args);
typedef void* tyArray_2PWyF6nokyTyhzmcY3ON3w[128];
struct tyObject_ToFreeQueue_5COJP8EWIaAuXvZlDbQZmw {
NI len;
pthread_mutex_t lock;
tyObject_Semaphore_sx9abLHOwgGDBH9bpoqw2ezw empty;
tyArray_2PWyF6nokyTyhzmcY3ON3w data;
};
struct tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw {
tyObject_Semaphore_sx9abLHOwgGDBH9bpoqw2ezw taskArrived;
tyObject_Semaphore_sx9abLHOwgGDBH9bpoqw2ezw taskStarted;
tyProc_fhqfcnDhIcLpBpSTVsWEZg f;
void* data;
NIM_BOOL ready;
NIM_BOOL initialized;
NIM_BOOL shutdown;
tyObject_ToFreeQueue_5COJP8EWIaAuXvZlDbQZmw q;
tyObject_Semaphore_sx9abLHOwgGDBH9bpoqw2ezw readyForTask;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_AwaitInfo_InuzBj4ASNnb8C8ZpRzfbA {
tyObject_Semaphore_sx9abLHOwgGDBH9bpoqw2ezw cv;
NI idx;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
Exception* up;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (Exception* e, void* ClE_0);
void* ClE_0;
} tyProc_KeeAOYBd84Ofsw6Y7LizaQ;
struct TSafePoint {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
tyProc_KeeAOYBd84Ofsw6Y7LizaQ raiseAction;
};
typedef N_NIMCALL_PTR(void, tyProc_nSqh6BBL9cSEu9bcR48Z72QA) (tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw* m);
struct tyObject_Thread_r8ouAaNLK65Vq7NM85n5aw {
tyObject_GcThread_hgJQSlfXDOK3SwSHjeZBXg* core;
pthread_t sys;
tyProc_nSqh6BBL9cSEu9bcR48Z72QA dataFn;
tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw* data;
};
typedef tyObject_Thread_r8ouAaNLK65Vq7NM85n5aw tyArray_TsQaT6n8o7agBt1qVLDj8w[256];
typedef tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw tyArray_5sGw9aMSI320X9cbYIDJFEOQ[256];
typedef tyObject_Thread_r8ouAaNLK65Vq7NM85n5aw tyArray_Vf5imvkL6TAbxWABRfm20A[32];
typedef tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw tyArray_W9bX58rb2TvIPS9bAprPBVQg[32];
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_ThreadPoolState_jN9benzGjAA9bryIHC1FGnZA {
NI calls;
};
typedef NU8 tyEnum_ThreadPoolAdvice_vD9cAMuSmfH29a9al5Q9cUZCig;
struct tyObject_FlowVarObj_a5vp0WwZohkMPdG8GkZciw {
  tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg Sup;
NimStringDesc* blob;
};
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc_hgOQFBQi19biNdOUUkFOOxA) (Exception* e);
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc_IIomJ6ptE6vfJ5zRbATgkQ;
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI lastSize;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* freeChunksList;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_SharedList_9cWkTIPQvNw7gFHMOEzMCLw {
tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw* head;
tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw* tail;
pthread_mutex_t lock;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
tyObject_SharedList_9cWkTIPQvNw7gFHMOEzMCLw toDispose;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tyProc_IIomJ6ptE6vfJ5zRbATgkQ cbproc, void* ClE_0);
void* ClE_0;
} tyProc_Ig6kXMs9apW5862wHsbFhGw;
struct tySequence_WF89a8QyKeDCh4DYWTmSiBg {
  TGenericSeq Sup;
  tyProc_IIomJ6ptE6vfJ5zRbATgkQ data[SEQ_DECL_SIZE];
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
typedef struct {tyProc_hgOQFBQi19biNdOUUkFOOxA localRaiseHook_EIvMhANBvB9cp2Ezvt29cADg;
tySequence_WF89a8QyKeDCh4DYWTmSiBg* threadDestructionHandlers_8OmU3x0fNdA0DLtOmU3kWw;
NI threadId_wzrdPYhtL9czkCWS4o9an9cRw;
TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
TSafePoint* excHandler_rqLlY5bs9atDw2OXYqJEn5g;
Exception* currException_9bVPeDJlYTi9bQApZpfH8wjg;
tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
NIM_BOOL envComputed_OC1kQm9aRvX8VnmaXglp57Q;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* environment_rnCB7Cc69bd2mlM49cn9czO2Q;
NIM_BOOL isSlave_t9a8wsVVRYqGEKhg1vb49b3g;
tyProc_Ig6kXMs9apW5862wHsbFhGw callSoonProc_9b9b4iUSd60RO2UqC52ifJ6A;
tyObject_PDispatchercolonObjectType__pnVRciItPqJkU9bkmY2UaWQ* gDisp_yIbBArLUsg2pBJkilx4yvg;
} NimThreadVars;
N_NIMCALL(void, initSemaphore_9czoqdg4eHIgtJ4wssK5YHA)(tyObject_Semaphore_sx9abLHOwgGDBH9bpoqw2ezw* cv);
static N_INLINE(void, initCond_cET5UPJTPSiflmV7IZS68Alocks)(pthread_cond_t* cond);
static N_INLINE(void, initLock_NyibMGWEvLI6dmuAjxN9brAlocks)(pthread_mutex_t* lock);
static N_INLINE(void, destroySemaphore_ZRg3Z8DVlD9bBm5kQEOnV7Qthreadpool)(tyObject_Semaphore_sx9abLHOwgGDBH9bpoqw2ezw* cv);
static N_INLINE(void, deinitCond_cET5UPJTPSiflmV7IZS68A_2locks)(pthread_cond_t* cond);
static N_INLINE(void, deinitLock_NyibMGWEvLI6dmuAjxN9brA_2locks)(pthread_mutex_t* lock);
N_NIMCALL(void, await_9czoqdg4eHIgtJ4wssK5YHA_2)(tyObject_Semaphore_sx9abLHOwgGDBH9bpoqw2ezw* cv);
N_NIMCALL(void, acquire_c9cbvs4ShkxrwmQmnY63PGA)(pthread_mutex_t* lock);
static N_INLINE(void, wait_1jWf7NqlMVz9aQJMRL9bTm9bQlocks)(pthread_cond_t* cond, pthread_mutex_t* lock);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(void, release_c9cbvs4ShkxrwmQmnY63PGA_2)(pthread_mutex_t* lock);
N_NIMCALL(void, signal_9czoqdg4eHIgtJ4wssK5YHA_3)(tyObject_Semaphore_sx9abLHOwgGDBH9bpoqw2ezw* cv);
static N_INLINE(NI, addInt)(NI a, NI b);
static N_INLINE(void, signal_cET5UPJTPSiflmV7IZS68A_3locks)(pthread_cond_t* cond);
static N_INLINE(void, barrierEnter)(Barrier* b);
static N_INLINE(void, barrierLeave)(Barrier* b);
static N_INLINE(NI, atomicInc_4E9cxwuunx9aiL7vj9bdy8WvAsystem)(NI* memLoc, NI x);
static N_INLINE(void, openBarrier)(Barrier* b);
N_NIMCALL(void, closeBarrier)(Barrier* b);
N_NIMCALL(void, await_v7HeuUBcnpz8vQGjcNl2Zg)(tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg* fv);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void*, GetThreadLocalVars)(void);
static N_INLINE(void*, threadVarGetValue_F5t3jb8jndWAZxsO5Ba9bHwsystem)(pthread_key_t s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NIM_BOOL, selectWorker_BW1ODxSJ4rN4KmfdYS8AFw)(tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw* w, tyProc_fhqfcnDhIcLpBpSTVsWEZg fn, void* data);
N_NIMCALL(void, cleanFlowVars_YsEpsvk4M2H0cFOPo7KYiA)(tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw* w);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(void, nimGCunref)(void* p);
N_NIMCALL(void, wakeupWorkerToProcessQueue_YsEpsvk4M2H0cFOPo7KYiA_2)(tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw* w);
static N_INLINE(void, cpuRelax_IZ2oOmqdsYQ7vixQGKSDcA_3system)(void);
N_NIMCALL(void, colonanonymous__RN9c4f80Dl8mVIo1K9bSACqA)(void* w, void* a);
N_NIMCALL(void, finished_v7HeuUBcnpz8vQGjcNl2Zg_2)(tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg* fv);
N_NOINLINE(void, raiseAssert_PpfSiTIeNpMAb9a5o6SglJw_2)(NimStringDesc* msg);
N_NIMCALL(void, nimFlowVarCreateSemaphore)(tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg* fv);
N_NIMCALL(void, nimFlowVarSignal)(tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg* fv);
N_NIMCALL(NI, awaitAny_vcBumXfLEGmomLN3bbmA5w)(tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg** flowVars, NI flowVarsLen_0);
N_NIMCALL(NIM_BOOL, isReady_k9cvjOLQv59bGjlW9ar7G4pOQ)(tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg* fv);
N_NIMCALL(void, nimArgsPassingDone)(void* p);
N_NIMCALL(void, slave_ZLEiMrITYl7xqyEhA5iC1g)(tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw* w);
N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(void, setFrame)(TFrame* s);
N_NIMCALL(void, reraiseException)(void);
static N_INLINE(NI, atomicDec_4E9cxwuunx9aiL7vj9bdy8WvA_2system)(NI* memLoc, NI x);
N_NIMCALL(void, distinguishedSlave_ZLEiMrITYl7xqyEhA5iC1g_2)(tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw* w);
N_NIMCALL(void, setMinPoolSize_i9c9c5F2sCRS4GypusVk8uIQ)(NI size);
N_NIMCALL(void, setMaxPoolSize_i9c9c5F2sCRS4GypusVk8uIQ_2)(NI size);
N_NIMCALL(void, createThread_M9ct0f7CQiyyVF9ahBe3fSlw)(tyObject_Thread_r8ouAaNLK65Vq7NM85n5aw* t, tyProc_nSqh6BBL9cSEu9bcR48Z72QA tp, tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw* param);
N_NOCONV(void*, threadProcWrapper_2AvjU29bJvs3FXJIcnmn4Kg)(void* closure);
N_NIMCALL(void, threadProcWrapStackFrame_t0lnloO9aBTBU0elWgvMSlw)(tyObject_Thread_r8ouAaNLK65Vq7NM85n5aw* thrd);
N_NIMCALL(void, threadProcWrapDispatch_t0lnloO9aBTBU0elWgvMSlw_2)(tyObject_Thread_r8ouAaNLK65Vq7NM85n5aw* thrd);
N_NOINLINE(void, activateWorkerThread_gZGpMQ9anM43sp7cjLJQjLg)(NI i);
N_NOINLINE(void, activateDistinguishedThread_gZGpMQ9anM43sp7cjLJQjLg_2)(NI i);
N_NIMCALL(void, setup_p4oO1XgRwu6WxNojgsXntg)(void);
N_NIMCALL(NI, ncpicountProcessors)(void);
N_NIMCALL(NIM_BOOL, preferSpawn_Jvod3sf15qssvdMH82j5dg)(void);
N_NIMCALL(void, nimSpawn3)(tyProc_fhqfcnDhIcLpBpSTVsWEZg fn, void* data);
N_NIMCALL(NIM_BOOL, tryAcquire_9bPySkj6HXfWNB4ampKcs9bg)(pthread_mutex_t* lock);
N_NIMCALL(tyEnum_ThreadPoolAdvice_vD9cAMuSmfH29a9al5Q9cUZCig, advice_9bmaXUZIEfSc9ax0Tn2TlQng)(tyObject_ThreadPoolState_jN9benzGjAA9bryIHC1FGnZA* s);
N_NIMCALL(void, nimSpawn4)(tyProc_fhqfcnDhIcLpBpSTVsWEZg fn, void* data, NI id);
N_NIMCALL(void, sync_p4oO1XgRwu6WxNojgsXntg_2)(void);
N_NIMCALL(void, fvFinalizer_W4h8xN17XW4JRY8Mrf8lfg)(tyObject_FlowVarObj_a5vp0WwZohkMPdG8GkZciw* fv);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef_VAHnGVFOjU5gFagNSbMOOg)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
extern pthread_key_t globalsSlot_ciXDZu9c27pHpCRMoz4RIgw;
NI currentPoolSize_ErccdOg9batM6rAb3hYbfxA;
NI maxPoolSize_I5gWiq7COu2xfOvex9aGTWw;
NI minPoolSize_L9a7W9byTjVXeXKRg5OtqNTg;
tyObject_Semaphore_sx9abLHOwgGDBH9bpoqw2ezw gSomeReady_RyUdpNfPQUpKmQaHtWHYoA;
tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw* readyWorker_BT69aUhVoxO4qq9b8EinSVNA;
pthread_mutex_t numSlavesLock_WtiE83BZa1NBG7G2g8ZnmA;
NI numSlavesRunning_ptIe6dS9bOnWPjIrLSfTasw;
NI numSlavesWaiting_fTOoJ83E0W3d2BkhxhQFwg;
tyArray_TsQaT6n8o7agBt1qVLDj8w workers_bezHuru9a1bEti2XBmfodvA;
tyArray_5sGw9aMSI320X9cbYIDJFEOQ workersData_R5YxoJYCt3PvKeJGhluUDQ;
tyArray_Vf5imvkL6TAbxWABRfm20A distinguished_PEEgL9bODGVNNubj61abNQA;
tyArray_W9bX58rb2TvIPS9bAprPBVQg distinguishedData_Lqsi7ieuVktaO9acMSZyorQ;
TNimType NTI_AqHEWWcw2VBFjoa2Hp8Akw_;
TNimType NTI_sx9abLHOwgGDBH9bpoqw2ezw_;
extern TNimType NTI_keOjwH3s9bnYBEeyteQLwbw_;
extern TNimType NTI_9bxnxao7MiiLOwO9aLAh9a3og_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
TNimType NTI_fhqfcnDhIcLpBpSTVsWEZg_;
extern TNimType NTI_vr5DoT1jILTGdRlYv1OYpw_;
extern TNimType NTI_VaVACK0bpYmqIQ0mKcHfQQ_;
TNimType NTI_5COJP8EWIaAuXvZlDbQZmw_;
TNimType NTI_2PWyF6nokyTyhzmcY3ON3w_;
TNimType NTI_CyNApV6Mfiphj5eUnH5G1A_;
tyObject_ThreadPoolState_jN9benzGjAA9bryIHC1FGnZA state_7PVqgO4qfT36l9bZ9a9cqhD9bA;
pthread_mutex_t stateLock_Of3qxka1C2uLE9anKCj52kA;
pthread_mutex_t distinguishedLock_lPmqsqhMalxIWA0zwhlpFg;
extern TNimType NTI_13RNkKqUOX1TtorOUlKtqA_;
TNimType NTI_CJfwFDAb1ST4bu6G9bMAYbg_;
TNimType NTI_InuzBj4ASNnb8C8ZpRzfbA_;
TNimType NTI_lFbunaQx9b6UMGaLkOEMqfQ_;
TNimType NTI_a5vp0WwZohkMPdG8GkZciw_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
TNimType NTI_VAHnGVFOjU5gFagNSbMOOg_;
STRING_LITERAL(TM_Qzgg5NBLvccay07XFph3Rw_6, "isNil(fv.ai) flowVar is still attached to an \'awaitAny\'", 55);
STRING_LITERAL(TM_Qzgg5NBLvccay07XFph3Rw_12, "not w.ready ", 12);

static N_INLINE(void, initCond_cET5UPJTPSiflmV7IZS68Alocks)(pthread_cond_t* cond) {
	pthread_cond_init(cond, NIM_NIL);
}

static N_INLINE(void, initLock_NyibMGWEvLI6dmuAjxN9brAlocks)(pthread_mutex_t* lock) {
	pthread_mutex_init(lock, NIM_NIL);
}

N_NIMCALL(void, initSemaphore_9czoqdg4eHIgtJ4wssK5YHA)(tyObject_Semaphore_sx9abLHOwgGDBH9bpoqw2ezw* cv) {
	initCond_cET5UPJTPSiflmV7IZS68Alocks((&(*cv).c));
	initLock_NyibMGWEvLI6dmuAjxN9brAlocks((&(*cv).L));
}

static N_INLINE(void, deinitCond_cET5UPJTPSiflmV7IZS68A_2locks)(pthread_cond_t* cond) {
	pthread_cond_destroy(cond);
}

static N_INLINE(void, deinitLock_NyibMGWEvLI6dmuAjxN9brA_2locks)(pthread_mutex_t* lock) {
	pthread_mutex_destroy(lock);
}

static N_INLINE(void, destroySemaphore_ZRg3Z8DVlD9bBm5kQEOnV7Qthreadpool)(tyObject_Semaphore_sx9abLHOwgGDBH9bpoqw2ezw* cv) {
	deinitCond_cET5UPJTPSiflmV7IZS68A_2locks((&(*cv).c));
	deinitLock_NyibMGWEvLI6dmuAjxN9brA_2locks((&(*cv).L));
}

static N_INLINE(void, wait_1jWf7NqlMVz9aQJMRL9bTm9bQlocks)(pthread_cond_t* cond, pthread_mutex_t* lock) {
	pthread_cond_wait(cond, lock);
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_NIMCALL(void, await_9czoqdg4eHIgtJ4wssK5YHA_2)(tyObject_Semaphore_sx9abLHOwgGDBH9bpoqw2ezw* cv) {
	NI TM_Qzgg5NBLvccay07XFph3Rw_2;
	acquire_c9cbvs4ShkxrwmQmnY63PGA((&(*cv).L));
	{
		while (1) {
			if (!((*cv).counter <= ((NI) 0))) goto LA2;
			wait_1jWf7NqlMVz9aQJMRL9bTm9bQlocks((&(*cv).c), (&(*cv).L));
		} LA2: ;
	}
	TM_Qzgg5NBLvccay07XFph3Rw_2 = subInt((*cv).counter, ((NI) 1));
	(*cv).counter = (NI)(TM_Qzgg5NBLvccay07XFph3Rw_2);
	release_c9cbvs4ShkxrwmQmnY63PGA_2((&(*cv).L));
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, signal_cET5UPJTPSiflmV7IZS68A_3locks)(pthread_cond_t* cond) {
	pthread_cond_signal(cond);
}

N_NIMCALL(void, signal_9czoqdg4eHIgtJ4wssK5YHA_3)(tyObject_Semaphore_sx9abLHOwgGDBH9bpoqw2ezw* cv) {
	NI TM_Qzgg5NBLvccay07XFph3Rw_3;
	acquire_c9cbvs4ShkxrwmQmnY63PGA((&(*cv).L));
	TM_Qzgg5NBLvccay07XFph3Rw_3 = addInt((*cv).counter, ((NI) 1));
	(*cv).counter = (NI)(TM_Qzgg5NBLvccay07XFph3Rw_3);
	release_c9cbvs4ShkxrwmQmnY63PGA_2((&(*cv).L));
	signal_cET5UPJTPSiflmV7IZS68A_3locks((&(*cv).c));
}

static N_INLINE(void, barrierEnter)(Barrier* b) {
	NI TM_Qzgg5NBLvccay07XFph3Rw_4;
	TM_Qzgg5NBLvccay07XFph3Rw_4 = addInt((*b).entered, ((NI) 1));
	(*b).entered = (NI)(TM_Qzgg5NBLvccay07XFph3Rw_4);
}

static N_INLINE(NI, atomicInc_4E9cxwuunx9aiL7vj9bdy8WvAsystem)(NI* memLoc, NI x) {
	NI result;
	result = (NI)0;
	result = __atomic_add_fetch(memLoc, x, __ATOMIC_RELAXED);
	return result;
}

static N_INLINE(void, barrierLeave)(Barrier* b) {
	NI T1_;
	T1_ = (NI)0;
	T1_ = atomicInc_4E9cxwuunx9aiL7vj9bdy8WvAsystem((&(*b).left), ((NI) 1));
	__atomic_thread_fence(__ATOMIC_SEQ_CST);
	{
		NIM_BOOL T4_;
		T4_ = (NIM_BOOL)0;
		T4_ = (*b).interest;
		if (!(T4_)) goto LA5_;
		T4_ = ((*b).entered <= (*b).left);
		LA5_: ;
		if (!T4_) goto LA6_;
		signal_9czoqdg4eHIgtJ4wssK5YHA_3((&(*b).cv));
	}
	LA6_: ;
}

static N_INLINE(void, openBarrier)(Barrier* b) {
	(*b).entered = ((NI) 0);
	(*b).left = ((NI) 0);
	(*b).interest = NIM_FALSE;
}

N_NIMCALL(void, closeBarrier)(Barrier* b) {
	__atomic_thread_fence(__ATOMIC_SEQ_CST);
	{
		if (!!(((*b).left == (*b).entered))) goto LA3_;
		initSemaphore_9czoqdg4eHIgtJ4wssK5YHA((&(*b).cv));
		__atomic_thread_fence(__ATOMIC_SEQ_CST);
		(*b).interest = NIM_TRUE;
		__atomic_thread_fence(__ATOMIC_SEQ_CST);
		{
			while (1) {
				if (!!(((*b).left == (*b).entered))) goto LA6;
				await_9czoqdg4eHIgtJ4wssK5YHA_2((&(*b).cv));
			} LA6: ;
		}
		destroySemaphore_ZRg3Z8DVlD9bBm5kQEOnV7Qthreadpool((&(*b).cv));
	}
	LA3_: ;
}

static N_INLINE(void*, threadVarGetValue_F5t3jb8jndWAZxsO5Ba9bHwsystem)(pthread_key_t s) {
	void* result;
	result = (void*)0;
	result = pthread_getspecific(s);
	return result;
}

static N_INLINE(void*, GetThreadLocalVars)(void) {
	void* result;
	void* T1_;
	result = (void*)0;
	T1_ = (void*)0;
	T1_ = threadVarGetValue_F5t3jb8jndWAZxsO5Ba9bHwsystem(globalsSlot_ciXDZu9c27pHpCRMoz4RIgw);
	result = ((void*) ((*((tyObject_GcThread_hgJQSlfXDOK3SwSHjeZBXg*) (T1_))).tls));
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	NimThreadVars* NimTV_;
	NimTV_ = (NimThreadVars*) GetThreadLocalVars();
	T1_ = (NI)0;
	{
		if (!(NimTV_->framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*NimTV_->framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = NimTV_->framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	NimTV_->framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	NimThreadVars* NimTV_;
	NimTV_ = (NimThreadVars*) GetThreadLocalVars();
	NimTV_->framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*NimTV_->framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_NIMCALL(void, await_v7HeuUBcnpz8vQGjcNl2Zg)(tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg* fv) {
	nimfr_("await", "threadpool.nim");
	nimln_(136, "threadpool.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (*fv).usesSemaphore;
		if (!(T3_)) goto LA4_;
		T3_ = !((*fv).awaited);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(137, "threadpool.nim");
		(*fv).awaited = NIM_TRUE;
		nimln_(138, "threadpool.nim");
		await_9czoqdg4eHIgtJ4wssK5YHA_2((&(*fv).cv));
		nimln_(139, "threadpool.nim");
		destroySemaphore_ZRg3Z8DVlD9bBm5kQEOnV7Qthreadpool((&(*fv).cv));
	}
	LA5_: ;
	popFrame();
}

N_NIMCALL(NIM_BOOL, selectWorker_BW1ODxSJ4rN4KmfdYS8AFw)(tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw* w, tyProc_fhqfcnDhIcLpBpSTVsWEZg fn, void* data) {
	NIM_BOOL result;
	nimfr_("selectWorker", "threadpool.nim");
	result = (NIM_BOOL)0;
	nimln_(142, "threadpool.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = __sync_bool_compare_and_swap((&(*w).ready), NIM_TRUE, NIM_FALSE);
		if (!T3_) goto LA4_;
		nimln_(143, "threadpool.nim");
		(*w).data = data;
		nimln_(144, "threadpool.nim");
		(*w).f = fn;
		nimln_(145, "threadpool.nim");
		signal_9czoqdg4eHIgtJ4wssK5YHA_3((&(*w).taskArrived));
		nimln_(146, "threadpool.nim");
		await_9czoqdg4eHIgtJ4wssK5YHA_2((&(*w).taskStarted));
		nimln_(147, "threadpool.nim");
		result = NIM_TRUE;
	}
	LA4_: ;
	popFrame();
	return result;
}

N_NIMCALL(void, cleanFlowVars_YsEpsvk4M2H0cFOPo7KYiA)(tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw* w) {
	tyObject_ToFreeQueue_5COJP8EWIaAuXvZlDbQZmw* q;
	nimfr_("cleanFlowVars", "threadpool.nim");
	nimln_(150, "threadpool.nim");
	q = (&(*w).q);
	nimln_(151, "threadpool.nim");
	acquire_c9cbvs4ShkxrwmQmnY63PGA((&(*q).lock));
	{
		NI i;
		NI colontmp_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(152, "threadpool.nim");
		colontmp_ = subInt((*q).len, 1);
		nimln_(1986, "system.nim");
		res = ((NI) 0);
		{
			nimln_(1987, "system.nim");
			while (1) {
				NI TM_Qzgg5NBLvccay07XFph3Rw_5;
				if (!(res <= colontmp_)) goto LA3;
				nimln_(1988, "system.nim");
				i = res;
				nimln_(153, "threadpool.nim");
				if ((NU)(i) > (NU)(127)) raiseIndexError();
				nimGCunref(((RootObj*) ((*q).data[(i)- 0])));
				nimln_(1989, "system.nim");
				TM_Qzgg5NBLvccay07XFph3Rw_5 = addInt(res, ((NI) 1));
				res = (NI)(TM_Qzgg5NBLvccay07XFph3Rw_5);
			} LA3: ;
		}
	}
	nimln_(155, "threadpool.nim");
	(*q).len = ((NI) 0);
	nimln_(156, "threadpool.nim");
	release_c9cbvs4ShkxrwmQmnY63PGA_2((&(*q).lock));
	popFrame();
}

static N_INLINE(void, cpuRelax_IZ2oOmqdsYQ7vixQGKSDcA_3system)(void) {
	asm volatile("pause" ::: "memory");
}

N_NIMCALL(void, colonanonymous__RN9c4f80Dl8mVIo1K9bSACqA)(void* w, void* a) {
	tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw* w_2;
	nimfr_(":anonymous", "threadpool.nim");
	nimln_(166, "threadpool.nim");
	w_2 = ((tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw*) (w));
	nimln_(167, "threadpool.nim");
	cleanFlowVars_YsEpsvk4M2H0cFOPo7KYiA(w_2);
	nimln_(168, "threadpool.nim");
	signal_9czoqdg4eHIgtJ4wssK5YHA_3((&(*w_2).q.empty));
	popFrame();
}

N_NIMCALL(void, wakeupWorkerToProcessQueue_YsEpsvk4M2H0cFOPo7KYiA_2)(tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw* w) {
	nimfr_("wakeupWorkerToProcessQueue", "threadpool.nim");
	{
		nimln_(161, "threadpool.nim");
		while (1) {
			NIM_BOOL T3_;
			T3_ = (NIM_BOOL)0;
			T3_ = __sync_bool_compare_and_swap((&(*w).ready), NIM_TRUE, NIM_FALSE);
			if (!!(T3_)) goto LA2;
			nimln_(162, "threadpool.nim");
			cpuRelax_IZ2oOmqdsYQ7vixQGKSDcA_3system();
		} LA2: ;
	}
	nimln_(164, "threadpool.nim");
	(*w).data = NIM_NIL;
	nimln_(165, "threadpool.nim");
	(*w).f = colonanonymous__RN9c4f80Dl8mVIo1K9bSACqA;
	nimln_(169, "threadpool.nim");
	signal_9czoqdg4eHIgtJ4wssK5YHA_3((&(*w).taskArrived));
	popFrame();
}

N_NIMCALL(void, finished_v7HeuUBcnpz8vQGjcNl2Zg_2)(tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg* fv) {
	tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw* owner;
	tyObject_ToFreeQueue_5COJP8EWIaAuXvZlDbQZmw* q;
	NI TM_Qzgg5NBLvccay07XFph3Rw_7;
	nimfr_("finished", "threadpool.nim");
{	nimln_(172, "threadpool.nim");
	{
		if (!!(((*fv).ai == 0))) goto LA3_;
		raiseAssert_PpfSiTIeNpMAb9a5o6SglJw_2(((NimStringDesc*) &TM_Qzgg5NBLvccay07XFph3Rw_6));
	}
	LA3_: ;
	nimln_(176, "threadpool.nim");
	await_v7HeuUBcnpz8vQGjcNl2Zg(fv);
	nimln_(177, "threadpool.nim");
	{
		if (!((*fv).data == 0)) goto LA7_;
		goto BeforeRet_;
	}
	LA7_: ;
	nimln_(178, "threadpool.nim");
	owner = ((tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw*) ((*fv).owner));
	nimln_(179, "threadpool.nim");
	q = (&(*owner).q);
	nimln_(180, "threadpool.nim");
	acquire_c9cbvs4ShkxrwmQmnY63PGA((&(*q).lock));
	{
		nimln_(181, "threadpool.nim");
		while (1) {
			if (!!(((*q).len < ((NI) 128)))) goto LA10;
			nimln_(183, "threadpool.nim");
			release_c9cbvs4ShkxrwmQmnY63PGA_2((&(*q).lock));
			nimln_(184, "threadpool.nim");
			wakeupWorkerToProcessQueue_YsEpsvk4M2H0cFOPo7KYiA_2(owner);
			nimln_(185, "threadpool.nim");
			await_9czoqdg4eHIgtJ4wssK5YHA_2((&(*q).empty));
			nimln_(186, "threadpool.nim");
			acquire_c9cbvs4ShkxrwmQmnY63PGA((&(*q).lock));
		} LA10: ;
	}
	if ((NU)((*q).len) > (NU)(127)) raiseIndexError();
	nimln_(187, "threadpool.nim");
	(*q).data[((*q).len)- 0] = ((void*) ((*fv).data));
	nimln_(188, "threadpool.nim");
	TM_Qzgg5NBLvccay07XFph3Rw_7 = addInt((*q).len, ((NI) 1));
	(*q).len = (NI)(TM_Qzgg5NBLvccay07XFph3Rw_7);
	nimln_(189, "threadpool.nim");
	release_c9cbvs4ShkxrwmQmnY63PGA_2((&(*q).lock));
	nimln_(190, "threadpool.nim");
	(*fv).data = NIM_NIL;
	}BeforeRet_: ;
	popFrame();
}

N_NIMCALL(void, nimFlowVarCreateSemaphore)(tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg* fv) {
	nimfr_("nimFlowVarCreateSemaphore", "threadpool.nim");
	nimln_(198, "threadpool.nim");
	initSemaphore_9czoqdg4eHIgtJ4wssK5YHA((&(*fv).cv));
	nimln_(199, "threadpool.nim");
	(*fv).usesSemaphore = NIM_TRUE;
	popFrame();
}

N_NIMCALL(void, nimFlowVarSignal)(tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg* fv) {
	nimfr_("nimFlowVarSignal", "threadpool.nim");
	nimln_(202, "threadpool.nim");
	{
		NI TM_Qzgg5NBLvccay07XFph3Rw_8;
		nimln_(378, "system.nim");
		nimln_(202, "threadpool.nim");
		if (!!(((*fv).ai == NIM_NIL))) goto LA3_;
		nimln_(203, "threadpool.nim");
		acquire_c9cbvs4ShkxrwmQmnY63PGA((&(*(*fv).ai).cv.L));
		nimln_(204, "threadpool.nim");
		(*(*fv).ai).idx = (*fv).idx;
		nimln_(205, "threadpool.nim");
		TM_Qzgg5NBLvccay07XFph3Rw_8 = addInt((*(*fv).ai).cv.counter, ((NI) 1));
		(*(*fv).ai).cv.counter = (NI)(TM_Qzgg5NBLvccay07XFph3Rw_8);
		nimln_(206, "threadpool.nim");
		release_c9cbvs4ShkxrwmQmnY63PGA_2((&(*(*fv).ai).cv.L));
		nimln_(207, "threadpool.nim");
		signal_cET5UPJTPSiflmV7IZS68A_3locks((&(*(*fv).ai).cv.c));
	}
	LA3_: ;
	nimln_(208, "threadpool.nim");
	{
		if (!(*fv).usesSemaphore) goto LA7_;
		nimln_(209, "threadpool.nim");
		signal_9czoqdg4eHIgtJ4wssK5YHA_3((&(*fv).cv));
	}
	LA7_: ;
	popFrame();
}

N_NIMCALL(NI, awaitAny_vcBumXfLEGmomLN3bbmA5w)(tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg** flowVars, NI flowVarsLen_0) {
	NI result;
	tyObject_AwaitInfo_InuzBj4ASNnb8C8ZpRzfbA ai;
	NI conflicts;
	nimfr_("awaitAny", "threadpool.nim");
	result = (NI)0;
	memset((void*)(&ai), 0, sizeof(ai));
	nimln_(254, "threadpool.nim");
	initSemaphore_9czoqdg4eHIgtJ4wssK5YHA((&ai.cv));
	nimln_(255, "threadpool.nim");
	conflicts = ((NI) 0);
	{
		NI i;
		NI colontmp_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(256, "threadpool.nim");
		colontmp_ = (flowVarsLen_0-1);
		nimln_(1986, "system.nim");
		res = ((NI) 0);
		{
			nimln_(1987, "system.nim");
			while (1) {
				NI TM_Qzgg5NBLvccay07XFph3Rw_10;
				if (!(res <= colontmp_)) goto LA3;
				nimln_(1988, "system.nim");
				i = res;
				nimln_(257, "threadpool.nim");
				{
					NIM_BOOL T6_;
					if ((NU)(i) >= (NU)(flowVarsLen_0)) raiseIndexError();
					T6_ = (NIM_BOOL)0;
					T6_ = __sync_bool_compare_and_swap(&(*flowVars[i]).ai, NIM_NIL, (&ai));
					if (!T6_) goto LA7_;
					if ((NU)(i) >= (NU)(flowVarsLen_0)) raiseIndexError();
					nimln_(258, "threadpool.nim");
					(*flowVars[i]).idx = i;
				}
				goto LA4_;
				LA7_: ;
				{
					NI TM_Qzgg5NBLvccay07XFph3Rw_9;
					nimln_(260, "threadpool.nim");
					TM_Qzgg5NBLvccay07XFph3Rw_9 = addInt(conflicts, ((NI) 1));
					conflicts = (NI)(TM_Qzgg5NBLvccay07XFph3Rw_9);
				}
				LA4_: ;
				nimln_(1989, "system.nim");
				TM_Qzgg5NBLvccay07XFph3Rw_10 = addInt(res, ((NI) 1));
				res = (NI)(TM_Qzgg5NBLvccay07XFph3Rw_10);
			} LA3: ;
		}
	}
	nimln_(261, "threadpool.nim");
	{
		if (!(conflicts < flowVarsLen_0)) goto LA12_;
		nimln_(262, "threadpool.nim");
		await_9czoqdg4eHIgtJ4wssK5YHA_2((&ai.cv));
		nimln_(263, "threadpool.nim");
		result = ai.idx;
		{
			NI i_2;
			NI colontmp__2;
			NI res_2;
			i_2 = (NI)0;
			colontmp__2 = (NI)0;
			nimln_(264, "threadpool.nim");
			colontmp__2 = (flowVarsLen_0-1);
			nimln_(1986, "system.nim");
			res_2 = ((NI) 0);
			{
				nimln_(1987, "system.nim");
				while (1) {
					NIM_BOOL T17_;
					NI TM_Qzgg5NBLvccay07XFph3Rw_11;
					if (!(res_2 <= colontmp__2)) goto LA16;
					nimln_(1988, "system.nim");
					i_2 = res_2;
					nimln_(265, "threadpool.nim");
					if ((NU)(i_2) >= (NU)(flowVarsLen_0)) raiseIndexError();
					T17_ = (NIM_BOOL)0;
					T17_ = __sync_bool_compare_and_swap(&(*flowVars[i_2]).ai, (&ai), NIM_NIL);
					T17_;
					nimln_(1989, "system.nim");
					TM_Qzgg5NBLvccay07XFph3Rw_11 = addInt(res_2, ((NI) 1));
					res_2 = (NI)(TM_Qzgg5NBLvccay07XFph3Rw_11);
				} LA16: ;
			}
		}
	}
	goto LA10_;
	LA12_: ;
	{
		nimln_(267, "threadpool.nim");
		result = ((NI) -1);
	}
	LA10_: ;
	nimln_(268, "threadpool.nim");
	destroySemaphore_ZRg3Z8DVlD9bBm5kQEOnV7Qthreadpool((&ai.cv));
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, isReady_k9cvjOLQv59bGjlW9ar7G4pOQ)(tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg* fv) {
	NIM_BOOL result;
	nimfr_("isReady", "threadpool.nim");
	result = (NIM_BOOL)0;
	nimln_(274, "threadpool.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (*fv).usesSemaphore;
		if (!(T3_)) goto LA4_;
		T3_ = !((*fv).awaited);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(275, "threadpool.nim");
		acquire_c9cbvs4ShkxrwmQmnY63PGA((&(*fv).cv.L));
		nimln_(276, "threadpool.nim");
		result = (((NI) 0) < (*fv).cv.counter);
		nimln_(277, "threadpool.nim");
		release_c9cbvs4ShkxrwmQmnY63PGA_2((&(*fv).cv.L));
	}
	goto LA1_;
	LA5_: ;
	{
		nimln_(279, "threadpool.nim");
		result = NIM_TRUE;
	}
	LA1_: ;
	popFrame();
	return result;
}

N_NIMCALL(void, nimArgsPassingDone)(void* p) {
	tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw* w;
	nimfr_("nimArgsPassingDone", "threadpool.nim");
	nimln_(282, "threadpool.nim");
	w = ((tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw*) (p));
	nimln_(283, "threadpool.nim");
	signal_9czoqdg4eHIgtJ4wssK5YHA_3((&(*w).taskStarted));
	popFrame();
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	NimThreadVars* NimTV_;
	NimTV_ = (NimThreadVars*) GetThreadLocalVars();
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = NimTV_->excHandler_rqLlY5bs9atDw2OXYqJEn5g;
	NimTV_->excHandler_rqLlY5bs9atDw2OXYqJEn5g = s;
}

static N_INLINE(void, popSafePoint)(void) {
	NimThreadVars* NimTV_;
	NimTV_ = (NimThreadVars*) GetThreadLocalVars();
	NimTV_->excHandler_rqLlY5bs9atDw2OXYqJEn5g = (*NimTV_->excHandler_rqLlY5bs9atDw2OXYqJEn5g).prev;
}

static N_INLINE(void, setFrame)(TFrame* s) {
	NimThreadVars* NimTV_;
	NimTV_ = (NimThreadVars*) GetThreadLocalVars();
	NimTV_->framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
}

static N_INLINE(NI, atomicDec_4E9cxwuunx9aiL7vj9bdy8WvA_2system)(NI* memLoc, NI x) {
	NI result;
	result = (NI)0;
	result = __atomic_sub_fetch(memLoc, x, __ATOMIC_RELAXED);
	return result;
}

N_NIMCALL(void, slave_ZLEiMrITYl7xqyEhA5iC1g)(tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw* w) {
	NimThreadVars* NimTV_;
	nimfr_("slave", "threadpool.nim");
	NimTV_ = (NimThreadVars*) GetThreadLocalVars();
	nimln_(313, "threadpool.nim");
	NimTV_->isSlave_t9a8wsVVRYqGEKhg1vb49b3g = NIM_TRUE;
	{
		nimln_(314, "threadpool.nim");
		while (1) {
			TSafePoint TM_Qzgg5NBLvccay07XFph3Rw_13;
			TSafePoint TM_Qzgg5NBLvccay07XFph3Rw_15;
			nimln_(316, "threadpool.nim");
			__atomic_store_n((&(*w).ready), NIM_TRUE, __ATOMIC_SEQ_CST);
			nimln_(319, "threadpool.nim");
			readyWorker_BT69aUhVoxO4qq9b8EinSVNA = w;
			nimln_(320, "threadpool.nim");
			signal_9czoqdg4eHIgtJ4wssK5YHA_3((&gSomeReady_RyUdpNfPQUpKmQaHtWHYoA));
			nimln_(321, "threadpool.nim");
			await_9czoqdg4eHIgtJ4wssK5YHA_2((&(*w).taskArrived));
			nimln_(324, "threadpool.nim");
			{
				if (!!(!((*w).ready))) goto LA5_;
				failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_Qzgg5NBLvccay07XFph3Rw_12));
			}
			LA5_: ;
			nimln_(326, "threadpool.nim");
			acquire_c9cbvs4ShkxrwmQmnY63PGA((&numSlavesLock_WtiE83BZa1NBG7G2g8ZnmA));
			nimln_(67, "locks.nim");
			pushSafePoint(&TM_Qzgg5NBLvccay07XFph3Rw_13);
			TM_Qzgg5NBLvccay07XFph3Rw_13.status = _setjmp(TM_Qzgg5NBLvccay07XFph3Rw_13.context);
			if (TM_Qzgg5NBLvccay07XFph3Rw_13.status == 0) {
				NI TM_Qzgg5NBLvccay07XFph3Rw_14;
				nimln_(327, "threadpool.nim");
				TM_Qzgg5NBLvccay07XFph3Rw_14 = addInt(numSlavesRunning_ptIe6dS9bOnWPjIrLSfTasw, ((NI) 1));
				numSlavesRunning_ptIe6dS9bOnWPjIrLSfTasw = (NI)(TM_Qzgg5NBLvccay07XFph3Rw_14);
				popSafePoint();
			}
			else {
				popSafePoint();
				setFrame((TFrame*)&FR_);
			}
			{
				nimln_(326, "threadpool.nim");
				release_c9cbvs4ShkxrwmQmnY63PGA_2((&numSlavesLock_WtiE83BZa1NBG7G2g8ZnmA));
			}
			if (TM_Qzgg5NBLvccay07XFph3Rw_13.status != 0) reraiseException();
			nimln_(329, "threadpool.nim");
			(*w).f(((void*) (w)), (*w).data);
			nimln_(331, "threadpool.nim");
			acquire_c9cbvs4ShkxrwmQmnY63PGA((&numSlavesLock_WtiE83BZa1NBG7G2g8ZnmA));
			nimln_(67, "locks.nim");
			pushSafePoint(&TM_Qzgg5NBLvccay07XFph3Rw_15);
			TM_Qzgg5NBLvccay07XFph3Rw_15.status = _setjmp(TM_Qzgg5NBLvccay07XFph3Rw_15.context);
			if (TM_Qzgg5NBLvccay07XFph3Rw_15.status == 0) {
				NI TM_Qzgg5NBLvccay07XFph3Rw_16;
				nimln_(332, "threadpool.nim");
				TM_Qzgg5NBLvccay07XFph3Rw_16 = subInt(numSlavesRunning_ptIe6dS9bOnWPjIrLSfTasw, ((NI) 1));
				numSlavesRunning_ptIe6dS9bOnWPjIrLSfTasw = (NI)(TM_Qzgg5NBLvccay07XFph3Rw_16);
				popSafePoint();
			}
			else {
				popSafePoint();
				setFrame((TFrame*)&FR_);
			}
			{
				nimln_(331, "threadpool.nim");
				release_c9cbvs4ShkxrwmQmnY63PGA_2((&numSlavesLock_WtiE83BZa1NBG7G2g8ZnmA));
			}
			if (TM_Qzgg5NBLvccay07XFph3Rw_15.status != 0) reraiseException();
			nimln_(334, "threadpool.nim");
			{
				nimln_(378, "system.nim");
				nimln_(334, "threadpool.nim");
				if (!!(((*w).q.len == ((NI) 0)))) goto LA15_;
				cleanFlowVars_YsEpsvk4M2H0cFOPo7KYiA(w);
			}
			LA15_: ;
			nimln_(335, "threadpool.nim");
			{
				NI T21_;
				if (!(*w).shutdown) goto LA19_;
				nimln_(336, "threadpool.nim");
				(*w).shutdown = NIM_FALSE;
				nimln_(337, "threadpool.nim");
				T21_ = (NI)0;
				T21_ = atomicDec_4E9cxwuunx9aiL7vj9bdy8WvA_2system((&currentPoolSize_ErccdOg9batM6rAb3hYbfxA), ((NI) 1));
			}
			LA19_: ;
		}
	}
	popFrame();
}

N_NIMCALL(void, distinguishedSlave_ZLEiMrITYl7xqyEhA5iC1g_2)(tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw* w) {
	nimfr_("distinguishedSlave", "threadpool.nim");
	{
		nimln_(340, "threadpool.nim");
		while (1) {
			nimln_(342, "threadpool.nim");
			__atomic_store_n((&(*w).ready), NIM_TRUE, __ATOMIC_SEQ_CST);
			nimln_(345, "threadpool.nim");
			signal_9czoqdg4eHIgtJ4wssK5YHA_3((&(*w).readyForTask));
			nimln_(346, "threadpool.nim");
			await_9czoqdg4eHIgtJ4wssK5YHA_2((&(*w).taskArrived));
			nimln_(347, "threadpool.nim");
			{
				if (!!(!((*w).ready))) goto LA5_;
				failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_Qzgg5NBLvccay07XFph3Rw_12));
			}
			LA5_: ;
			nimln_(348, "threadpool.nim");
			(*w).f(((void*) (w)), (*w).data);
			nimln_(349, "threadpool.nim");
			{
				nimln_(378, "system.nim");
				nimln_(349, "threadpool.nim");
				if (!!(((*w).q.len == ((NI) 0)))) goto LA9_;
				cleanFlowVars_YsEpsvk4M2H0cFOPo7KYiA(w);
			}
			LA9_: ;
		}
	}
	popFrame();
}

N_NIMCALL(void, setMinPoolSize_i9c9c5F2sCRS4GypusVk8uIQ)(NI size) {
	nimfr_("setMinPoolSize", "threadpool.nim");
	nimln_(363, "threadpool.nim");
	minPoolSize_L9a7W9byTjVXeXKRg5OtqNTg = ((NI) (size));
	popFrame();
}

N_NIMCALL(void, setMaxPoolSize_i9c9c5F2sCRS4GypusVk8uIQ_2)(NI size) {
	nimfr_("setMaxPoolSize", "threadpool.nim");
	nimln_(368, "threadpool.nim");
	maxPoolSize_I5gWiq7COu2xfOvex9aGTWw = ((NI) (size));
	nimln_(369, "threadpool.nim");
	{
		if (!(maxPoolSize_I5gWiq7COu2xfOvex9aGTWw < currentPoolSize_ErccdOg9batM6rAb3hYbfxA)) goto LA3_;
		{
			NI i;
			NI colontmp_;
			NI TM_Qzgg5NBLvccay07XFph3Rw_17;
			NI res;
			i = (NI)0;
			colontmp_ = (NI)0;
			nimln_(370, "threadpool.nim");
			TM_Qzgg5NBLvccay07XFph3Rw_17 = subInt(currentPoolSize_ErccdOg9batM6rAb3hYbfxA, ((NI) 1));
			colontmp_ = (NI)(TM_Qzgg5NBLvccay07XFph3Rw_17);
			nimln_(1986, "system.nim");
			res = maxPoolSize_I5gWiq7COu2xfOvex9aGTWw;
			{
				nimln_(1987, "system.nim");
				while (1) {
					tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw* w;
					NI TM_Qzgg5NBLvccay07XFph3Rw_18;
					if (!(res <= colontmp_)) goto LA7;
					nimln_(1988, "system.nim");
					i = res;
					nimln_(371, "threadpool.nim");
					if ((NU)(i) > (NU)(255)) raiseIndexError();
					w = (&workersData_R5YxoJYCt3PvKeJGhluUDQ[(i)- 0]);
					nimln_(372, "threadpool.nim");
					(*w).shutdown = NIM_TRUE;
					nimln_(1989, "system.nim");
					TM_Qzgg5NBLvccay07XFph3Rw_18 = addInt(res, ((NI) 1));
					res = (NI)(TM_Qzgg5NBLvccay07XFph3Rw_18);
				} LA7: ;
			}
		}
	}
	LA3_: ;
	popFrame();
}

N_NOINLINE(void, activateWorkerThread_gZGpMQ9anM43sp7cjLJQjLg)(NI i) {
	nimfr_("activateWorkerThread", "threadpool.nim");
	nimln_(378, "threadpool.nim");
	if ((NU)(i) > (NU)(255)) raiseIndexError();
	initSemaphore_9czoqdg4eHIgtJ4wssK5YHA((&workersData_R5YxoJYCt3PvKeJGhluUDQ[(i)- 0].taskArrived));
	nimln_(379, "threadpool.nim");
	if ((NU)(i) > (NU)(255)) raiseIndexError();
	initSemaphore_9czoqdg4eHIgtJ4wssK5YHA((&workersData_R5YxoJYCt3PvKeJGhluUDQ[(i)- 0].taskStarted));
	if ((NU)(i) > (NU)(255)) raiseIndexError();
	nimln_(380, "threadpool.nim");
	workersData_R5YxoJYCt3PvKeJGhluUDQ[(i)- 0].initialized = NIM_TRUE;
	nimln_(381, "threadpool.nim");
	if ((NU)(i) > (NU)(255)) raiseIndexError();
	initSemaphore_9czoqdg4eHIgtJ4wssK5YHA((&workersData_R5YxoJYCt3PvKeJGhluUDQ[(i)- 0].q.empty));
	nimln_(382, "threadpool.nim");
	if ((NU)(i) > (NU)(255)) raiseIndexError();
	initLock_NyibMGWEvLI6dmuAjxN9brAlocks((&workersData_R5YxoJYCt3PvKeJGhluUDQ[(i)- 0].q.lock));
	nimln_(383, "threadpool.nim");
	if ((NU)(i) > (NU)(255)) raiseIndexError();
	if ((NU)(i) > (NU)(255)) raiseIndexError();
	createThread_M9ct0f7CQiyyVF9ahBe3fSlw((&workers_bezHuru9a1bEti2XBmfodvA[(i)- 0]), slave_ZLEiMrITYl7xqyEhA5iC1g, (&workersData_R5YxoJYCt3PvKeJGhluUDQ[(i)- 0]));
	popFrame();
}

N_NOINLINE(void, activateDistinguishedThread_gZGpMQ9anM43sp7cjLJQjLg_2)(NI i) {
	nimfr_("activateDistinguishedThread", "threadpool.nim");
	nimln_(390, "threadpool.nim");
	if ((NU)(i) > (NU)(31)) raiseIndexError();
	initSemaphore_9czoqdg4eHIgtJ4wssK5YHA((&distinguishedData_Lqsi7ieuVktaO9acMSZyorQ[(i)- 0].taskArrived));
	nimln_(391, "threadpool.nim");
	if ((NU)(i) > (NU)(31)) raiseIndexError();
	initSemaphore_9czoqdg4eHIgtJ4wssK5YHA((&distinguishedData_Lqsi7ieuVktaO9acMSZyorQ[(i)- 0].taskStarted));
	if ((NU)(i) > (NU)(31)) raiseIndexError();
	nimln_(392, "threadpool.nim");
	distinguishedData_Lqsi7ieuVktaO9acMSZyorQ[(i)- 0].initialized = NIM_TRUE;
	nimln_(393, "threadpool.nim");
	if ((NU)(i) > (NU)(31)) raiseIndexError();
	initSemaphore_9czoqdg4eHIgtJ4wssK5YHA((&distinguishedData_Lqsi7ieuVktaO9acMSZyorQ[(i)- 0].q.empty));
	nimln_(394, "threadpool.nim");
	if ((NU)(i) > (NU)(31)) raiseIndexError();
	initLock_NyibMGWEvLI6dmuAjxN9brAlocks((&distinguishedData_Lqsi7ieuVktaO9acMSZyorQ[(i)- 0].q.lock));
	nimln_(395, "threadpool.nim");
	if ((NU)(i) > (NU)(31)) raiseIndexError();
	initSemaphore_9czoqdg4eHIgtJ4wssK5YHA((&distinguishedData_Lqsi7ieuVktaO9acMSZyorQ[(i)- 0].readyForTask));
	nimln_(396, "threadpool.nim");
	if ((NU)(i) > (NU)(31)) raiseIndexError();
	if ((NU)(i) > (NU)(31)) raiseIndexError();
	createThread_M9ct0f7CQiyyVF9ahBe3fSlw((&distinguished_PEEgL9bODGVNNubj61abNQA[(i)- 0]), distinguishedSlave_ZLEiMrITYl7xqyEhA5iC1g_2, (&distinguishedData_Lqsi7ieuVktaO9acMSZyorQ[(i)- 0]));
	popFrame();
}

N_NIMCALL(void, setup_p4oO1XgRwu6WxNojgsXntg)(void) {
	NI p;
	nimfr_("setup", "threadpool.nim");
	nimln_(399, "threadpool.nim");
	p = ncpicountProcessors();
	nimln_(402, "threadpool.nim");
	currentPoolSize_ErccdOg9batM6rAb3hYbfxA = ((p <= ((NI) 256)) ? p : ((NI) 256));
	nimln_(403, "threadpool.nim");
	readyWorker_BT69aUhVoxO4qq9b8EinSVNA = (&workersData_R5YxoJYCt3PvKeJGhluUDQ[(((NI) 0))- 0]);
	{
		NI i;
		NI colontmp_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(404, "threadpool.nim");
		colontmp_ = subInt(currentPoolSize_ErccdOg9batM6rAb3hYbfxA, 1);
		nimln_(1986, "system.nim");
		res = ((NI) 0);
		{
			nimln_(1987, "system.nim");
			while (1) {
				NI TM_Qzgg5NBLvccay07XFph3Rw_22;
				if (!(res <= colontmp_)) goto LA3;
				nimln_(1988, "system.nim");
				i = res;
				nimln_(404, "threadpool.nim");
				activateWorkerThread_gZGpMQ9anM43sp7cjLJQjLg(i);
				nimln_(1989, "system.nim");
				TM_Qzgg5NBLvccay07XFph3Rw_22 = addInt(res, ((NI) 1));
				res = (NI)(TM_Qzgg5NBLvccay07XFph3Rw_22);
			} LA3: ;
		}
	}
	popFrame();
}

N_NIMCALL(NIM_BOOL, preferSpawn_Jvod3sf15qssvdMH82j5dg)(void) {
	NIM_BOOL result;
	nimfr_("preferSpawn", "threadpool.nim");
	result = (NIM_BOOL)0;
	nimln_(410, "threadpool.nim");
	result = (((NI) 0) < gSomeReady_RyUdpNfPQUpKmQaHtWHYoA.counter);
	popFrame();
	return result;
}

N_NIMCALL(void, nimSpawn3)(tyProc_fhqfcnDhIcLpBpSTVsWEZg fn, void* data) {
	NimThreadVars* NimTV_;
	nimfr_("nimSpawn3", "threadpool.nim");
{	NimTV_ = (NimThreadVars*) GetThreadLocalVars();
	{
		nimln_(447, "threadpool.nim");
		while (1) {
			nimln_(448, "threadpool.nim");
			{
				NIM_BOOL T5_;
				T5_ = (NIM_BOOL)0;
				T5_ = selectWorker_BW1ODxSJ4rN4KmfdYS8AFw(readyWorker_BT69aUhVoxO4qq9b8EinSVNA, fn, data);
				if (!T5_) goto LA6_;
				goto BeforeRet_;
			}
			LA6_: ;
			{
				NI i;
				NI colontmp_;
				NI res;
				i = (NI)0;
				colontmp_ = (NI)0;
				nimln_(449, "threadpool.nim");
				colontmp_ = subInt(currentPoolSize_ErccdOg9batM6rAb3hYbfxA, 1);
				nimln_(1986, "system.nim");
				res = ((NI) 0);
				{
					nimln_(1987, "system.nim");
					while (1) {
						NI TM_Qzgg5NBLvccay07XFph3Rw_23;
						if (!(res <= colontmp_)) goto LA10;
						nimln_(1988, "system.nim");
						i = res;
						nimln_(450, "threadpool.nim");
						{
							NIM_BOOL T13_;
							if ((NU)(i) > (NU)(255)) raiseIndexError();
							T13_ = (NIM_BOOL)0;
							T13_ = selectWorker_BW1ODxSJ4rN4KmfdYS8AFw((&workersData_R5YxoJYCt3PvKeJGhluUDQ[(i)- 0]), fn, data);
							if (!T13_) goto LA14_;
							goto BeforeRet_;
						}
						LA14_: ;
						nimln_(1989, "system.nim");
						TM_Qzgg5NBLvccay07XFph3Rw_23 = addInt(res, ((NI) 1));
						res = (NI)(TM_Qzgg5NBLvccay07XFph3Rw_23);
					} LA10: ;
				}
			}
			nimln_(454, "threadpool.nim");
			{
				NIM_BOOL T18_;
				T18_ = (NIM_BOOL)0;
				T18_ = (state_7PVqgO4qfT36l9bZ9a9cqhD9bA.calls < maxPoolSize_I5gWiq7COu2xfOvex9aGTWw);
				if (T18_) goto LA19_;
				T18_ = (((NI) ((NI)(state_7PVqgO4qfT36l9bZ9a9cqhD9bA.calls & ((NI) 127)))) == ((NI) 0));
				LA19_: ;
				if (!T18_) goto LA20_;
				nimln_(456, "threadpool.nim");
				{
					NIM_BOOL T24_;
					tyEnum_ThreadPoolAdvice_vD9cAMuSmfH29a9al5Q9cUZCig T27_;
					T24_ = (NIM_BOOL)0;
					T24_ = tryAcquire_9bPySkj6HXfWNB4ampKcs9bg((&stateLock_Of3qxka1C2uLE9anKCj52kA));
					if (!T24_) goto LA25_;
					nimln_(457, "threadpool.nim");
					T27_ = (tyEnum_ThreadPoolAdvice_vD9cAMuSmfH29a9al5Q9cUZCig)0;
					T27_ = advice_9bmaXUZIEfSc9ax0Tn2TlQng((&state_7PVqgO4qfT36l9bZ9a9cqhD9bA));
					switch (T27_) {
					case ((tyEnum_ThreadPoolAdvice_vD9cAMuSmfH29a9al5Q9cUZCig) 0):
					{
					}
					break;
					case ((tyEnum_ThreadPoolAdvice_vD9cAMuSmfH29a9al5Q9cUZCig) 1):
					{
						nimln_(460, "threadpool.nim");
						{
							tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw* w;
							NI T38_;
							if (!(currentPoolSize_ErccdOg9batM6rAb3hYbfxA < maxPoolSize_I5gWiq7COu2xfOvex9aGTWw)) goto LA32_;
							nimln_(461, "threadpool.nim");
							{
								if ((NU)(currentPoolSize_ErccdOg9batM6rAb3hYbfxA) > (NU)(255)) raiseIndexError();
								if (!!(workersData_R5YxoJYCt3PvKeJGhluUDQ[(currentPoolSize_ErccdOg9batM6rAb3hYbfxA)- 0].initialized)) goto LA36_;
								nimln_(462, "threadpool.nim");
								activateWorkerThread_gZGpMQ9anM43sp7cjLJQjLg(currentPoolSize_ErccdOg9batM6rAb3hYbfxA);
							}
							LA36_: ;
							nimln_(463, "threadpool.nim");
							if ((NU)(currentPoolSize_ErccdOg9batM6rAb3hYbfxA) > (NU)(255)) raiseIndexError();
							w = (&workersData_R5YxoJYCt3PvKeJGhluUDQ[(currentPoolSize_ErccdOg9batM6rAb3hYbfxA)- 0]);
							nimln_(464, "threadpool.nim");
							T38_ = (NI)0;
							T38_ = atomicInc_4E9cxwuunx9aiL7vj9bdy8WvAsystem((&currentPoolSize_ErccdOg9batM6rAb3hYbfxA), ((NI) 1));
							nimln_(465, "threadpool.nim");
							{
								NIM_BOOL T41_;
								T41_ = (NIM_BOOL)0;
								T41_ = selectWorker_BW1ODxSJ4rN4KmfdYS8AFw(w, fn, data);
								if (!T41_) goto LA42_;
								nimln_(466, "threadpool.nim");
								release_c9cbvs4ShkxrwmQmnY63PGA_2((&stateLock_Of3qxka1C2uLE9anKCj52kA));
								nimln_(467, "threadpool.nim");
								goto BeforeRet_;
							}
							LA42_: ;
						}
						LA32_: ;
					}
					break;
					case ((tyEnum_ThreadPoolAdvice_vD9cAMuSmfH29a9al5Q9cUZCig) 2):
					{
						nimln_(470, "threadpool.nim");
						{
							tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw* w_2;
							NI TM_Qzgg5NBLvccay07XFph3Rw_24;
							if (!(minPoolSize_L9a7W9byTjVXeXKRg5OtqNTg < currentPoolSize_ErccdOg9batM6rAb3hYbfxA)) goto LA47_;
							nimln_(471, "threadpool.nim");
							TM_Qzgg5NBLvccay07XFph3Rw_24 = subInt(currentPoolSize_ErccdOg9batM6rAb3hYbfxA, ((NI) 1));
							if ((NU)((NI)(TM_Qzgg5NBLvccay07XFph3Rw_24)) > (NU)(255)) raiseIndexError();
							w_2 = (&workersData_R5YxoJYCt3PvKeJGhluUDQ[((NI)(TM_Qzgg5NBLvccay07XFph3Rw_24))- 0]);
							nimln_(472, "threadpool.nim");
							(*w_2).shutdown = NIM_TRUE;
						}
						LA47_: ;
					}
					break;
					}
					nimln_(474, "threadpool.nim");
					release_c9cbvs4ShkxrwmQmnY63PGA_2((&stateLock_Of3qxka1C2uLE9anKCj52kA));
				}
				LA25_: ;
			}
			LA20_: ;
			nimln_(487, "threadpool.nim");
			{
				TSafePoint TM_Qzgg5NBLvccay07XFph3Rw_25;
				if (!NimTV_->isSlave_t9a8wsVVRYqGEKhg1vb49b3g) goto LA51_;
				nimln_(490, "threadpool.nim");
				acquire_c9cbvs4ShkxrwmQmnY63PGA((&numSlavesLock_WtiE83BZa1NBG7G2g8ZnmA));
				nimln_(67, "locks.nim");
				pushSafePoint(&TM_Qzgg5NBLvccay07XFph3Rw_25);
				TM_Qzgg5NBLvccay07XFph3Rw_25.status = _setjmp(TM_Qzgg5NBLvccay07XFph3Rw_25.context);
				if (TM_Qzgg5NBLvccay07XFph3Rw_25.status == 0) {
					NI TM_Qzgg5NBLvccay07XFph3Rw_27;
					nimln_(491, "threadpool.nim");
					{
						NI TM_Qzgg5NBLvccay07XFph3Rw_26;
						TM_Qzgg5NBLvccay07XFph3Rw_26 = addInt(numSlavesWaiting_fTOoJ83E0W3d2BkhxhQFwg, ((NI) 1));
						if (!(numSlavesRunning_ptIe6dS9bOnWPjIrLSfTasw <= (NI)(TM_Qzgg5NBLvccay07XFph3Rw_26))) goto LA56_;
						nimln_(495, "threadpool.nim");
						{
							tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw* w_3;
							NI T66_;
							if (!(currentPoolSize_ErccdOg9batM6rAb3hYbfxA < maxPoolSize_I5gWiq7COu2xfOvex9aGTWw)) goto LA60_;
							nimln_(496, "threadpool.nim");
							{
								if ((NU)(currentPoolSize_ErccdOg9batM6rAb3hYbfxA) > (NU)(255)) raiseIndexError();
								if (!!(workersData_R5YxoJYCt3PvKeJGhluUDQ[(currentPoolSize_ErccdOg9batM6rAb3hYbfxA)- 0].initialized)) goto LA64_;
								nimln_(497, "threadpool.nim");
								activateWorkerThread_gZGpMQ9anM43sp7cjLJQjLg(currentPoolSize_ErccdOg9batM6rAb3hYbfxA);
							}
							LA64_: ;
							nimln_(498, "threadpool.nim");
							if ((NU)(currentPoolSize_ErccdOg9batM6rAb3hYbfxA) > (NU)(255)) raiseIndexError();
							w_3 = (&workersData_R5YxoJYCt3PvKeJGhluUDQ[(currentPoolSize_ErccdOg9batM6rAb3hYbfxA)- 0]);
							nimln_(499, "threadpool.nim");
							T66_ = (NI)0;
							T66_ = atomicInc_4E9cxwuunx9aiL7vj9bdy8WvAsystem((&currentPoolSize_ErccdOg9batM6rAb3hYbfxA), ((NI) 1));
							nimln_(500, "threadpool.nim");
							{
								NIM_BOOL T69_;
								T69_ = (NIM_BOOL)0;
								T69_ = selectWorker_BW1ODxSJ4rN4KmfdYS8AFw(w_3, fn, data);
								if (!T69_) goto LA70_;
								nimln_(501, "threadpool.nim");
								popSafePoint();
								nimln_(490, "threadpool.nim");
								release_c9cbvs4ShkxrwmQmnY63PGA_2((&numSlavesLock_WtiE83BZa1NBG7G2g8ZnmA));
								goto BeforeRet_;
							}
							LA70_: ;
						}
						goto LA58_;
						LA60_: ;
						{
						}
						LA58_: ;
					}
					LA56_: ;
					nimln_(507, "threadpool.nim");
					TM_Qzgg5NBLvccay07XFph3Rw_27 = addInt(numSlavesWaiting_fTOoJ83E0W3d2BkhxhQFwg, ((NI) 1));
					numSlavesWaiting_fTOoJ83E0W3d2BkhxhQFwg = (NI)(TM_Qzgg5NBLvccay07XFph3Rw_27);
					popSafePoint();
				}
				else {
					popSafePoint();
					setFrame((TFrame*)&FR_);
				}
				{
					nimln_(490, "threadpool.nim");
					release_c9cbvs4ShkxrwmQmnY63PGA_2((&numSlavesLock_WtiE83BZa1NBG7G2g8ZnmA));
				}
				if (TM_Qzgg5NBLvccay07XFph3Rw_25.status != 0) reraiseException();
			}
			LA51_: ;
			nimln_(509, "threadpool.nim");
			await_9czoqdg4eHIgtJ4wssK5YHA_2((&gSomeReady_RyUdpNfPQUpKmQaHtWHYoA));
			nimln_(511, "threadpool.nim");
			{
				TSafePoint TM_Qzgg5NBLvccay07XFph3Rw_28;
				if (!NimTV_->isSlave_t9a8wsVVRYqGEKhg1vb49b3g) goto LA77_;
				nimln_(512, "threadpool.nim");
				acquire_c9cbvs4ShkxrwmQmnY63PGA((&numSlavesLock_WtiE83BZa1NBG7G2g8ZnmA));
				nimln_(67, "locks.nim");
				pushSafePoint(&TM_Qzgg5NBLvccay07XFph3Rw_28);
				TM_Qzgg5NBLvccay07XFph3Rw_28.status = _setjmp(TM_Qzgg5NBLvccay07XFph3Rw_28.context);
				if (TM_Qzgg5NBLvccay07XFph3Rw_28.status == 0) {
					NI TM_Qzgg5NBLvccay07XFph3Rw_29;
					nimln_(513, "threadpool.nim");
					TM_Qzgg5NBLvccay07XFph3Rw_29 = subInt(numSlavesWaiting_fTOoJ83E0W3d2BkhxhQFwg, ((NI) 1));
					numSlavesWaiting_fTOoJ83E0W3d2BkhxhQFwg = (NI)(TM_Qzgg5NBLvccay07XFph3Rw_29);
					popSafePoint();
				}
				else {
					popSafePoint();
					setFrame((TFrame*)&FR_);
				}
				{
					nimln_(512, "threadpool.nim");
					release_c9cbvs4ShkxrwmQmnY63PGA_2((&numSlavesLock_WtiE83BZa1NBG7G2g8ZnmA));
				}
				if (TM_Qzgg5NBLvccay07XFph3Rw_28.status != 0) reraiseException();
			}
			LA77_: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
}

N_NIMCALL(void, nimSpawn4)(tyProc_fhqfcnDhIcLpBpSTVsWEZg fn, void* data, NI id) {
	nimfr_("nimSpawn4", "threadpool.nim");
	nimln_(521, "threadpool.nim");
	acquire_c9cbvs4ShkxrwmQmnY63PGA((&distinguishedLock_lPmqsqhMalxIWA0zwhlpFg));
	nimln_(522, "threadpool.nim");
	{
		if (!!(distinguishedData_Lqsi7ieuVktaO9acMSZyorQ[(id)- 0].initialized)) goto LA3_;
		nimln_(523, "threadpool.nim");
		activateDistinguishedThread_gZGpMQ9anM43sp7cjLJQjLg_2(((NI) (id)));
	}
	LA3_: ;
	nimln_(524, "threadpool.nim");
	release_c9cbvs4ShkxrwmQmnY63PGA_2((&distinguishedLock_lPmqsqhMalxIWA0zwhlpFg));
	{
		nimln_(525, "threadpool.nim");
		while (1) {
			nimln_(526, "threadpool.nim");
			{
				NIM_BOOL T9_;
				T9_ = (NIM_BOOL)0;
				T9_ = selectWorker_BW1ODxSJ4rN4KmfdYS8AFw((&distinguishedData_Lqsi7ieuVktaO9acMSZyorQ[(id)- 0]), fn, data);
				if (!T9_) goto LA10_;
				goto LA5;
			}
			LA10_: ;
			nimln_(527, "threadpool.nim");
			await_9czoqdg4eHIgtJ4wssK5YHA_2((&distinguishedData_Lqsi7ieuVktaO9acMSZyorQ[(id)- 0].readyForTask));
		}
	} LA5: ;
	popFrame();
}

N_NIMCALL(void, sync_p4oO1XgRwu6WxNojgsXntg_2)(void) {
	NI toRelease;
	nimfr_("sync", "threadpool.nim");
	nimln_(533, "threadpool.nim");
	toRelease = ((NI) 0);
	{
		nimln_(534, "threadpool.nim");
		while (1) {
			NIM_BOOL allReady;
			NI TM_Qzgg5NBLvccay07XFph3Rw_31;
			nimln_(535, "threadpool.nim");
			allReady = NIM_TRUE;
			{
				NI i;
				NI colontmp_;
				NI res;
				i = (NI)0;
				colontmp_ = (NI)0;
				nimln_(536, "threadpool.nim");
				colontmp_ = subInt(currentPoolSize_ErccdOg9batM6rAb3hYbfxA, 1);
				nimln_(1986, "system.nim");
				res = ((NI) 0);
				{
					nimln_(1987, "system.nim");
					while (1) {
						NIM_BOOL T10_;
						NI TM_Qzgg5NBLvccay07XFph3Rw_30;
						if (!(res <= colontmp_)) goto LA5;
						nimln_(1988, "system.nim");
						i = res;
						nimln_(537, "threadpool.nim");
						{
							if (!!(allReady)) goto LA8_;
							goto LA3;
						}
						LA8_: ;
						nimln_(538, "threadpool.nim");
						T10_ = (NIM_BOOL)0;
						T10_ = allReady;
						if (!(T10_)) goto LA11_;
						if ((NU)(i) > (NU)(255)) raiseIndexError();
						T10_ = workersData_R5YxoJYCt3PvKeJGhluUDQ[(i)- 0].ready;
						LA11_: ;
						allReady = T10_;
						nimln_(1989, "system.nim");
						TM_Qzgg5NBLvccay07XFph3Rw_30 = addInt(res, ((NI) 1));
						res = (NI)(TM_Qzgg5NBLvccay07XFph3Rw_30);
					} LA5: ;
				}
			} LA3: ;
			nimln_(539, "threadpool.nim");
			{
				if (!allReady) goto LA14_;
				goto LA1;
			}
			LA14_: ;
			nimln_(540, "threadpool.nim");
			await_9czoqdg4eHIgtJ4wssK5YHA_2((&gSomeReady_RyUdpNfPQUpKmQaHtWHYoA));
			nimln_(541, "threadpool.nim");
			TM_Qzgg5NBLvccay07XFph3Rw_31 = addInt(toRelease, ((NI) 1));
			toRelease = (NI)(TM_Qzgg5NBLvccay07XFph3Rw_31);
		}
	} LA1: ;
	{
		NI i_2;
		NI i_3;
		i_2 = (NI)0;
		nimln_(3832, "system.nim");
		i_3 = ((NI) 0);
		{
			nimln_(3833, "system.nim");
			while (1) {
				NI TM_Qzgg5NBLvccay07XFph3Rw_32;
				if (!(i_3 < toRelease)) goto LA18;
				nimln_(3834, "system.nim");
				i_2 = i_3;
				nimln_(544, "threadpool.nim");
				signal_9czoqdg4eHIgtJ4wssK5YHA_3((&gSomeReady_RyUdpNfPQUpKmQaHtWHYoA));
				nimln_(3835, "system.nim");
				TM_Qzgg5NBLvccay07XFph3Rw_32 = addInt(i_3, ((NI) 1));
				i_3 = (NI)(TM_Qzgg5NBLvccay07XFph3Rw_32);
			} LA18: ;
		}
	}
	popFrame();
}

N_NIMCALL(void, fvFinalizer_W4h8xN17XW4JRY8Mrf8lfg)(tyObject_FlowVarObj_a5vp0WwZohkMPdG8GkZciw* fv) {
	tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg* T1_;
	nimfr_("fvFinalizer", "threadpool.nim");
	nimln_(192, "threadpool.nim");
	T1_ = (tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg*)0;
	T1_ = &fv->Sup;
	finished_v7HeuUBcnpz8vQGjcNl2Zg_2(T1_);
	popFrame();
}
static N_NIMCALL(void, Marker_tyRef_VAHnGVFOjU5gFagNSbMOOg)(void* p, NI op) {
	tyObject_FlowVarObj_a5vp0WwZohkMPdG8GkZciw* a;
	a = (tyObject_FlowVarObj_a5vp0WwZohkMPdG8GkZciw*)p;
	nimGCvisit((void*)(*a).blob, op);
}

N_NIMCALL(tyObject_FlowVarObj_a5vp0WwZohkMPdG8GkZciw*, nimCreateFlowVar_xO39aB5u4tZXwMOqMul3KoQ)(void) {
	tyObject_FlowVarObj_a5vp0WwZohkMPdG8GkZciw* result;
	nimfr_("nimCreateFlowVar", "threadpool.nim");
	result = (tyObject_FlowVarObj_a5vp0WwZohkMPdG8GkZciw*)0;
	nimln_(195, "threadpool.nim");
	result = (tyObject_FlowVarObj_a5vp0WwZohkMPdG8GkZciw*) newObj((&NTI_VAHnGVFOjU5gFagNSbMOOg_), sizeof(tyObject_FlowVarObj_a5vp0WwZohkMPdG8GkZciw));
	(*result).Sup.Sup.m_type = (&NTI_a5vp0WwZohkMPdG8GkZciw_);
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, roof__LbfEYJu3cF61FE9coTsJenA)(tyObject_FlowVarObj_a5vp0WwZohkMPdG8GkZciw* fv) {
	NimStringDesc* result;
	tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg* T1_;
	nimfr_("^", "threadpool.nim");
	result = (NimStringDesc*)0;
	nimln_(238, "threadpool.nim");
	T1_ = (tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg*)0;
	T1_ = &fv->Sup;
	await_v7HeuUBcnpz8vQGjcNl2Zg(T1_);
	nimln_(241, "threadpool.nim");
	result = copyString(((NimStringDesc*) ((*fv).Sup.data)));
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_threadpoolInit000)(void) {
	nimfr_("threadpool", "threadpool.nim");
	nimln_(295, "threadpool.nim");
	maxPoolSize_I5gWiq7COu2xfOvex9aGTWw = ((NI) 256);
	nimln_(296, "threadpool.nim");
	minPoolSize_L9a7W9byTjVXeXKRg5OtqNTg = ((NI) 4);
	nimln_(308, "threadpool.nim");
	initLock_NyibMGWEvLI6dmuAjxN9brAlocks((&numSlavesLock_WtiE83BZa1NBG7G2g8ZnmA));
	nimln_(310, "threadpool.nim");
	initSemaphore_9czoqdg4eHIgtJ4wssK5YHA((&gSomeReady_RyUdpNfPQUpKmQaHtWHYoA));
	nimln_(443, "threadpool.nim");
	initLock_NyibMGWEvLI6dmuAjxN9brAlocks((&stateLock_Of3qxka1C2uLE9anKCj52kA));
	nimln_(518, "threadpool.nim");
	initLock_NyibMGWEvLI6dmuAjxN9brAlocks((&distinguishedLock_lPmqsqhMalxIWA0zwhlpFg));
	nimln_(546, "threadpool.nim");
	setup_p4oO1XgRwu6WxNojgsXntg();
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_threadpoolDatInit000)(void) {
static TNimNode* TM_Qzgg5NBLvccay07XFph3Rw_19[9];
static TNimNode* TM_Qzgg5NBLvccay07XFph3Rw_20[3];
static TNimNode* TM_Qzgg5NBLvccay07XFph3Rw_21[4];
static TNimNode* TM_Qzgg5NBLvccay07XFph3Rw_33[8];
static TNimNode* TM_Qzgg5NBLvccay07XFph3Rw_34[2];
static TNimNode TM_Qzgg5NBLvccay07XFph3Rw_0[32];
NTI_AqHEWWcw2VBFjoa2Hp8Akw_.size = sizeof(tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw);
NTI_AqHEWWcw2VBFjoa2Hp8Akw_.kind = 18;
NTI_AqHEWWcw2VBFjoa2Hp8Akw_.base = 0;
NTI_AqHEWWcw2VBFjoa2Hp8Akw_.flags = 3;
TM_Qzgg5NBLvccay07XFph3Rw_19[0] = &TM_Qzgg5NBLvccay07XFph3Rw_0[1];
NTI_sx9abLHOwgGDBH9bpoqw2ezw_.size = sizeof(tyObject_Semaphore_sx9abLHOwgGDBH9bpoqw2ezw);
NTI_sx9abLHOwgGDBH9bpoqw2ezw_.kind = 18;
NTI_sx9abLHOwgGDBH9bpoqw2ezw_.base = 0;
NTI_sx9abLHOwgGDBH9bpoqw2ezw_.flags = 3;
TM_Qzgg5NBLvccay07XFph3Rw_20[0] = &TM_Qzgg5NBLvccay07XFph3Rw_0[3];
TM_Qzgg5NBLvccay07XFph3Rw_0[3].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[3].offset = offsetof(tyObject_Semaphore_sx9abLHOwgGDBH9bpoqw2ezw, c);
TM_Qzgg5NBLvccay07XFph3Rw_0[3].typ = (&NTI_keOjwH3s9bnYBEeyteQLwbw_);
TM_Qzgg5NBLvccay07XFph3Rw_0[3].name = "c";
TM_Qzgg5NBLvccay07XFph3Rw_20[1] = &TM_Qzgg5NBLvccay07XFph3Rw_0[4];
TM_Qzgg5NBLvccay07XFph3Rw_0[4].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[4].offset = offsetof(tyObject_Semaphore_sx9abLHOwgGDBH9bpoqw2ezw, L);
TM_Qzgg5NBLvccay07XFph3Rw_0[4].typ = (&NTI_9bxnxao7MiiLOwO9aLAh9a3og_);
TM_Qzgg5NBLvccay07XFph3Rw_0[4].name = "L";
TM_Qzgg5NBLvccay07XFph3Rw_20[2] = &TM_Qzgg5NBLvccay07XFph3Rw_0[5];
TM_Qzgg5NBLvccay07XFph3Rw_0[5].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[5].offset = offsetof(tyObject_Semaphore_sx9abLHOwgGDBH9bpoqw2ezw, counter);
TM_Qzgg5NBLvccay07XFph3Rw_0[5].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_Qzgg5NBLvccay07XFph3Rw_0[5].name = "counter";
TM_Qzgg5NBLvccay07XFph3Rw_0[2].len = 3; TM_Qzgg5NBLvccay07XFph3Rw_0[2].kind = 2; TM_Qzgg5NBLvccay07XFph3Rw_0[2].sons = &TM_Qzgg5NBLvccay07XFph3Rw_20[0];
NTI_sx9abLHOwgGDBH9bpoqw2ezw_.node = &TM_Qzgg5NBLvccay07XFph3Rw_0[2];
TM_Qzgg5NBLvccay07XFph3Rw_0[1].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[1].offset = offsetof(tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw, taskArrived);
TM_Qzgg5NBLvccay07XFph3Rw_0[1].typ = (&NTI_sx9abLHOwgGDBH9bpoqw2ezw_);
TM_Qzgg5NBLvccay07XFph3Rw_0[1].name = "taskArrived";
TM_Qzgg5NBLvccay07XFph3Rw_19[1] = &TM_Qzgg5NBLvccay07XFph3Rw_0[6];
TM_Qzgg5NBLvccay07XFph3Rw_0[6].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[6].offset = offsetof(tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw, taskStarted);
TM_Qzgg5NBLvccay07XFph3Rw_0[6].typ = (&NTI_sx9abLHOwgGDBH9bpoqw2ezw_);
TM_Qzgg5NBLvccay07XFph3Rw_0[6].name = "taskStarted";
TM_Qzgg5NBLvccay07XFph3Rw_19[2] = &TM_Qzgg5NBLvccay07XFph3Rw_0[7];
NTI_fhqfcnDhIcLpBpSTVsWEZg_.size = sizeof(tyProc_fhqfcnDhIcLpBpSTVsWEZg);
NTI_fhqfcnDhIcLpBpSTVsWEZg_.kind = 25;
NTI_fhqfcnDhIcLpBpSTVsWEZg_.base = 0;
NTI_fhqfcnDhIcLpBpSTVsWEZg_.flags = 3;
TM_Qzgg5NBLvccay07XFph3Rw_0[7].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[7].offset = offsetof(tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw, f);
TM_Qzgg5NBLvccay07XFph3Rw_0[7].typ = (&NTI_fhqfcnDhIcLpBpSTVsWEZg_);
TM_Qzgg5NBLvccay07XFph3Rw_0[7].name = "f";
TM_Qzgg5NBLvccay07XFph3Rw_19[3] = &TM_Qzgg5NBLvccay07XFph3Rw_0[8];
TM_Qzgg5NBLvccay07XFph3Rw_0[8].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[8].offset = offsetof(tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw, data);
TM_Qzgg5NBLvccay07XFph3Rw_0[8].typ = (&NTI_vr5DoT1jILTGdRlYv1OYpw_);
TM_Qzgg5NBLvccay07XFph3Rw_0[8].name = "data";
TM_Qzgg5NBLvccay07XFph3Rw_19[4] = &TM_Qzgg5NBLvccay07XFph3Rw_0[9];
TM_Qzgg5NBLvccay07XFph3Rw_0[9].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[9].offset = offsetof(tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw, ready);
TM_Qzgg5NBLvccay07XFph3Rw_0[9].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_Qzgg5NBLvccay07XFph3Rw_0[9].name = "ready";
TM_Qzgg5NBLvccay07XFph3Rw_19[5] = &TM_Qzgg5NBLvccay07XFph3Rw_0[10];
TM_Qzgg5NBLvccay07XFph3Rw_0[10].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[10].offset = offsetof(tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw, initialized);
TM_Qzgg5NBLvccay07XFph3Rw_0[10].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_Qzgg5NBLvccay07XFph3Rw_0[10].name = "initialized";
TM_Qzgg5NBLvccay07XFph3Rw_19[6] = &TM_Qzgg5NBLvccay07XFph3Rw_0[11];
TM_Qzgg5NBLvccay07XFph3Rw_0[11].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[11].offset = offsetof(tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw, shutdown);
TM_Qzgg5NBLvccay07XFph3Rw_0[11].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_Qzgg5NBLvccay07XFph3Rw_0[11].name = "shutdown";
TM_Qzgg5NBLvccay07XFph3Rw_19[7] = &TM_Qzgg5NBLvccay07XFph3Rw_0[12];
NTI_5COJP8EWIaAuXvZlDbQZmw_.size = sizeof(tyObject_ToFreeQueue_5COJP8EWIaAuXvZlDbQZmw);
NTI_5COJP8EWIaAuXvZlDbQZmw_.kind = 18;
NTI_5COJP8EWIaAuXvZlDbQZmw_.base = 0;
NTI_5COJP8EWIaAuXvZlDbQZmw_.flags = 3;
TM_Qzgg5NBLvccay07XFph3Rw_21[0] = &TM_Qzgg5NBLvccay07XFph3Rw_0[14];
TM_Qzgg5NBLvccay07XFph3Rw_0[14].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[14].offset = offsetof(tyObject_ToFreeQueue_5COJP8EWIaAuXvZlDbQZmw, len);
TM_Qzgg5NBLvccay07XFph3Rw_0[14].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_Qzgg5NBLvccay07XFph3Rw_0[14].name = "len";
TM_Qzgg5NBLvccay07XFph3Rw_21[1] = &TM_Qzgg5NBLvccay07XFph3Rw_0[15];
TM_Qzgg5NBLvccay07XFph3Rw_0[15].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[15].offset = offsetof(tyObject_ToFreeQueue_5COJP8EWIaAuXvZlDbQZmw, lock);
TM_Qzgg5NBLvccay07XFph3Rw_0[15].typ = (&NTI_9bxnxao7MiiLOwO9aLAh9a3og_);
TM_Qzgg5NBLvccay07XFph3Rw_0[15].name = "lock";
TM_Qzgg5NBLvccay07XFph3Rw_21[2] = &TM_Qzgg5NBLvccay07XFph3Rw_0[16];
TM_Qzgg5NBLvccay07XFph3Rw_0[16].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[16].offset = offsetof(tyObject_ToFreeQueue_5COJP8EWIaAuXvZlDbQZmw, empty);
TM_Qzgg5NBLvccay07XFph3Rw_0[16].typ = (&NTI_sx9abLHOwgGDBH9bpoqw2ezw_);
TM_Qzgg5NBLvccay07XFph3Rw_0[16].name = "empty";
TM_Qzgg5NBLvccay07XFph3Rw_21[3] = &TM_Qzgg5NBLvccay07XFph3Rw_0[17];
NTI_2PWyF6nokyTyhzmcY3ON3w_.size = sizeof(tyArray_2PWyF6nokyTyhzmcY3ON3w);
NTI_2PWyF6nokyTyhzmcY3ON3w_.kind = 16;
NTI_2PWyF6nokyTyhzmcY3ON3w_.base = (&NTI_vr5DoT1jILTGdRlYv1OYpw_);
NTI_2PWyF6nokyTyhzmcY3ON3w_.flags = 3;
TM_Qzgg5NBLvccay07XFph3Rw_0[17].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[17].offset = offsetof(tyObject_ToFreeQueue_5COJP8EWIaAuXvZlDbQZmw, data);
TM_Qzgg5NBLvccay07XFph3Rw_0[17].typ = (&NTI_2PWyF6nokyTyhzmcY3ON3w_);
TM_Qzgg5NBLvccay07XFph3Rw_0[17].name = "data";
TM_Qzgg5NBLvccay07XFph3Rw_0[13].len = 4; TM_Qzgg5NBLvccay07XFph3Rw_0[13].kind = 2; TM_Qzgg5NBLvccay07XFph3Rw_0[13].sons = &TM_Qzgg5NBLvccay07XFph3Rw_21[0];
NTI_5COJP8EWIaAuXvZlDbQZmw_.node = &TM_Qzgg5NBLvccay07XFph3Rw_0[13];
TM_Qzgg5NBLvccay07XFph3Rw_0[12].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[12].offset = offsetof(tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw, q);
TM_Qzgg5NBLvccay07XFph3Rw_0[12].typ = (&NTI_5COJP8EWIaAuXvZlDbQZmw_);
TM_Qzgg5NBLvccay07XFph3Rw_0[12].name = "q";
TM_Qzgg5NBLvccay07XFph3Rw_19[8] = &TM_Qzgg5NBLvccay07XFph3Rw_0[18];
TM_Qzgg5NBLvccay07XFph3Rw_0[18].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[18].offset = offsetof(tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw, readyForTask);
TM_Qzgg5NBLvccay07XFph3Rw_0[18].typ = (&NTI_sx9abLHOwgGDBH9bpoqw2ezw_);
TM_Qzgg5NBLvccay07XFph3Rw_0[18].name = "readyForTask";
TM_Qzgg5NBLvccay07XFph3Rw_0[0].len = 9; TM_Qzgg5NBLvccay07XFph3Rw_0[0].kind = 2; TM_Qzgg5NBLvccay07XFph3Rw_0[0].sons = &TM_Qzgg5NBLvccay07XFph3Rw_19[0];
NTI_AqHEWWcw2VBFjoa2Hp8Akw_.node = &TM_Qzgg5NBLvccay07XFph3Rw_0[0];
NTI_CyNApV6Mfiphj5eUnH5G1A_.size = sizeof(tyObject_Worker_AqHEWWcw2VBFjoa2Hp8Akw*);
NTI_CyNApV6Mfiphj5eUnH5G1A_.kind = 21;
NTI_CyNApV6Mfiphj5eUnH5G1A_.base = (&NTI_AqHEWWcw2VBFjoa2Hp8Akw_);
NTI_CyNApV6Mfiphj5eUnH5G1A_.flags = 3;
NTI_CJfwFDAb1ST4bu6G9bMAYbg_.size = sizeof(tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg);
NTI_CJfwFDAb1ST4bu6G9bMAYbg_.kind = 17;
NTI_CJfwFDAb1ST4bu6G9bMAYbg_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
NTI_CJfwFDAb1ST4bu6G9bMAYbg_.flags = 1;
TM_Qzgg5NBLvccay07XFph3Rw_33[0] = &TM_Qzgg5NBLvccay07XFph3Rw_0[20];
TM_Qzgg5NBLvccay07XFph3Rw_0[20].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[20].offset = offsetof(tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg, ready);
TM_Qzgg5NBLvccay07XFph3Rw_0[20].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_Qzgg5NBLvccay07XFph3Rw_0[20].name = "ready";
TM_Qzgg5NBLvccay07XFph3Rw_33[1] = &TM_Qzgg5NBLvccay07XFph3Rw_0[21];
TM_Qzgg5NBLvccay07XFph3Rw_0[21].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[21].offset = offsetof(tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg, usesSemaphore);
TM_Qzgg5NBLvccay07XFph3Rw_0[21].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_Qzgg5NBLvccay07XFph3Rw_0[21].name = "usesSemaphore";
TM_Qzgg5NBLvccay07XFph3Rw_33[2] = &TM_Qzgg5NBLvccay07XFph3Rw_0[22];
TM_Qzgg5NBLvccay07XFph3Rw_0[22].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[22].offset = offsetof(tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg, awaited);
TM_Qzgg5NBLvccay07XFph3Rw_0[22].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_Qzgg5NBLvccay07XFph3Rw_0[22].name = "awaited";
TM_Qzgg5NBLvccay07XFph3Rw_33[3] = &TM_Qzgg5NBLvccay07XFph3Rw_0[23];
TM_Qzgg5NBLvccay07XFph3Rw_0[23].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[23].offset = offsetof(tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg, cv);
TM_Qzgg5NBLvccay07XFph3Rw_0[23].typ = (&NTI_sx9abLHOwgGDBH9bpoqw2ezw_);
TM_Qzgg5NBLvccay07XFph3Rw_0[23].name = "cv";
TM_Qzgg5NBLvccay07XFph3Rw_33[4] = &TM_Qzgg5NBLvccay07XFph3Rw_0[24];
NTI_InuzBj4ASNnb8C8ZpRzfbA_.size = sizeof(tyObject_AwaitInfo_InuzBj4ASNnb8C8ZpRzfbA);
NTI_InuzBj4ASNnb8C8ZpRzfbA_.kind = 18;
NTI_InuzBj4ASNnb8C8ZpRzfbA_.base = 0;
NTI_InuzBj4ASNnb8C8ZpRzfbA_.flags = 3;
TM_Qzgg5NBLvccay07XFph3Rw_34[0] = &TM_Qzgg5NBLvccay07XFph3Rw_0[26];
TM_Qzgg5NBLvccay07XFph3Rw_0[26].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[26].offset = offsetof(tyObject_AwaitInfo_InuzBj4ASNnb8C8ZpRzfbA, cv);
TM_Qzgg5NBLvccay07XFph3Rw_0[26].typ = (&NTI_sx9abLHOwgGDBH9bpoqw2ezw_);
TM_Qzgg5NBLvccay07XFph3Rw_0[26].name = "cv";
TM_Qzgg5NBLvccay07XFph3Rw_34[1] = &TM_Qzgg5NBLvccay07XFph3Rw_0[27];
TM_Qzgg5NBLvccay07XFph3Rw_0[27].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[27].offset = offsetof(tyObject_AwaitInfo_InuzBj4ASNnb8C8ZpRzfbA, idx);
TM_Qzgg5NBLvccay07XFph3Rw_0[27].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_Qzgg5NBLvccay07XFph3Rw_0[27].name = "idx";
TM_Qzgg5NBLvccay07XFph3Rw_0[25].len = 2; TM_Qzgg5NBLvccay07XFph3Rw_0[25].kind = 2; TM_Qzgg5NBLvccay07XFph3Rw_0[25].sons = &TM_Qzgg5NBLvccay07XFph3Rw_34[0];
NTI_InuzBj4ASNnb8C8ZpRzfbA_.node = &TM_Qzgg5NBLvccay07XFph3Rw_0[25];
NTI_lFbunaQx9b6UMGaLkOEMqfQ_.size = sizeof(tyObject_AwaitInfo_InuzBj4ASNnb8C8ZpRzfbA*);
NTI_lFbunaQx9b6UMGaLkOEMqfQ_.kind = 21;
NTI_lFbunaQx9b6UMGaLkOEMqfQ_.base = (&NTI_InuzBj4ASNnb8C8ZpRzfbA_);
NTI_lFbunaQx9b6UMGaLkOEMqfQ_.flags = 3;
TM_Qzgg5NBLvccay07XFph3Rw_0[24].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[24].offset = offsetof(tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg, ai);
TM_Qzgg5NBLvccay07XFph3Rw_0[24].typ = (&NTI_lFbunaQx9b6UMGaLkOEMqfQ_);
TM_Qzgg5NBLvccay07XFph3Rw_0[24].name = "ai";
TM_Qzgg5NBLvccay07XFph3Rw_33[5] = &TM_Qzgg5NBLvccay07XFph3Rw_0[28];
TM_Qzgg5NBLvccay07XFph3Rw_0[28].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[28].offset = offsetof(tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg, idx);
TM_Qzgg5NBLvccay07XFph3Rw_0[28].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_Qzgg5NBLvccay07XFph3Rw_0[28].name = "idx";
TM_Qzgg5NBLvccay07XFph3Rw_33[6] = &TM_Qzgg5NBLvccay07XFph3Rw_0[29];
TM_Qzgg5NBLvccay07XFph3Rw_0[29].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[29].offset = offsetof(tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg, data);
TM_Qzgg5NBLvccay07XFph3Rw_0[29].typ = (&NTI_vr5DoT1jILTGdRlYv1OYpw_);
TM_Qzgg5NBLvccay07XFph3Rw_0[29].name = "data";
TM_Qzgg5NBLvccay07XFph3Rw_33[7] = &TM_Qzgg5NBLvccay07XFph3Rw_0[30];
TM_Qzgg5NBLvccay07XFph3Rw_0[30].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[30].offset = offsetof(tyObject_FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg, owner);
TM_Qzgg5NBLvccay07XFph3Rw_0[30].typ = (&NTI_vr5DoT1jILTGdRlYv1OYpw_);
TM_Qzgg5NBLvccay07XFph3Rw_0[30].name = "owner";
TM_Qzgg5NBLvccay07XFph3Rw_0[19].len = 8; TM_Qzgg5NBLvccay07XFph3Rw_0[19].kind = 2; TM_Qzgg5NBLvccay07XFph3Rw_0[19].sons = &TM_Qzgg5NBLvccay07XFph3Rw_33[0];
NTI_CJfwFDAb1ST4bu6G9bMAYbg_.node = &TM_Qzgg5NBLvccay07XFph3Rw_0[19];
NTI_a5vp0WwZohkMPdG8GkZciw_.size = sizeof(tyObject_FlowVarObj_a5vp0WwZohkMPdG8GkZciw);
NTI_a5vp0WwZohkMPdG8GkZciw_.kind = 17;
NTI_a5vp0WwZohkMPdG8GkZciw_.base = (&NTI_CJfwFDAb1ST4bu6G9bMAYbg_);
TM_Qzgg5NBLvccay07XFph3Rw_0[31].kind = 1;
TM_Qzgg5NBLvccay07XFph3Rw_0[31].offset = offsetof(tyObject_FlowVarObj_a5vp0WwZohkMPdG8GkZciw, blob);
TM_Qzgg5NBLvccay07XFph3Rw_0[31].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_Qzgg5NBLvccay07XFph3Rw_0[31].name = "blob";
NTI_a5vp0WwZohkMPdG8GkZciw_.node = &TM_Qzgg5NBLvccay07XFph3Rw_0[31];
NTI_VAHnGVFOjU5gFagNSbMOOg_.size = sizeof(tyObject_FlowVarObj_a5vp0WwZohkMPdG8GkZciw*);
NTI_VAHnGVFOjU5gFagNSbMOOg_.kind = 22;
NTI_VAHnGVFOjU5gFagNSbMOOg_.base = (&NTI_a5vp0WwZohkMPdG8GkZciw_);
NTI_VAHnGVFOjU5gFagNSbMOOg_.marker = Marker_tyRef_VAHnGVFOjU5gFagNSbMOOg;
(&NTI_VAHnGVFOjU5gFagNSbMOOg_)->finalizer = (void*)fvFinalizer_W4h8xN17XW4JRY8Mrf8lfg;
}

